### ISSUE TITLE
1.16.5-forge-36.1.0 Stuck on white screen

### ISSUE THREAD

**Issue by jammmy2** [PojavLauncherTeam/PojavLauncher_iOS#114]
I’m on ios 14 my phone is Iphone 7
![AE281B79-7E15-4FBE-8E2D-0E647567C285](https://user-images.githubusercontent.com/81497901/112740146-25218500-8fad-11eb-919b-93ed0ed4e608.png)

I’m on ios 14 my phone is Iphone 7
2021-03-28 09:55:26.585 PojavLauncher[2284:542566] [Pre-init] Beginning JVM launch
2021-03-28 09:55:26.586 PojavLauncher[2284:542566] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2021-03-28 09:55:26.587 PojavLauncher[2284:542566] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:
2021-03-28 09:55:26.587 PojavLauncher[2284:542566] [Pre-init] Reading custom JVM args (overrideargs.txt), opened=0
2021-03-28 09:55:26.591 PojavLauncher[2284:542566] [Init] Found JLI lib
2021-03-28 09:55:26.591 PojavLauncher[2284:542566] [Init] Calling JLI_Launch
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Pre-init] Beginning JVM launch
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Pre-init] OpenGL library name: libgl4es_114.dylib
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Init] Found JLI lib
2021-03-28 09:55:26.593 PojavLauncher[2284:542575] [Init] Calling JLI_Launch
[0.070s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b7c0000-0x000000016b7cc000).
[0.070s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-03-28 09:55:27.108 PojavLauncher[2284:542566] libpojavexec loaded from vm=0x104f31e50
Finding a version
Selected Minecraft version: 1.16.5-forge-36.1.0
Downloading version list
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Downloading 1.16.5-forge-36.1.0.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading 1.16.5-forge-36.1.0.jar
2021-03-28 09:55:44.092 PojavLauncher[2284:542566] MGLKViewController viewDidLoad
2021-03-28 09:55:44.093 PojavLauncher[2284:542566] Error: could not read "default.json", fallbacking to default control.
No such file or directory
2021-03-28 09:55:44.140 PojavLauncher[2284:542566] Received SurfaceViewController callback, width=1334, height=750
Saving GLES context
Launching Minecraft 1.16.5-forge-36.1.0
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
2021-03-28 09:55:44.455 PojavLauncher[2284:542566] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x102d86d10>)
Args init finished. Now starting game
2021-03-28 09:55:45.002 PojavLauncher[2284:542566] MGLKViewController viewDidAppear
2021-03-28 09:55:45.002 PojavLauncher[2284:542566] MGLKViewController pause
2021-03-28 09:55:45.003 PojavLauncher[2284:542566] MGLKViewController resume
2021-03-28 09:55:45.014 PojavLauncher[2284:542566] MGLKViewController pause
2021-03-28 01:55:47,256 Thread-1 WARN Advanced terminal features are not available in this environment
[01:55:47] [Thread-1/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, jammmy , --version, 1.16.5, --gameDir, /var/mobile/Documents/minecraft, --assetsDir, /var/mobile/Documents/minecraft/assets, --assetIndex, 1.16, --uuid, 0, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --fullscreen]
[01:55:47] [Thread-1/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16 by N/A
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/var/mobile/Documents/minecraft/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[01:55:48] [Thread-1/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[01:55:48] [Thread-1/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/var/mobile/Documents/minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
2021-03-28 09:55:48.443 PojavLauncher[2284:542694] EGLBridge: Initialized!
2021-03-28 09:55:48.443 PojavLauncher[2284:542694] EGLBridge: EGLDisplay=0x102d8a5b0, EGLSurface=0x102d8eb20
2021-03-28 09:55:48.445 PojavLauncher[2284:542694] Using CTX pointer=0x1030e4000, shareCtx=NULL
[01:55:48] [Thread-1/INFO] [STDOUT/]: [org.lwjgl.glfw.GLFW:glfwShowWindow:1030]: GLFW: Showing window 4346232832, width=1334, height=750, x=0, y=0, 
2021-03-28 09:55:48.474 PojavLauncher[2284:542713] Making current on window 0x1030e4000
2021-03-28 09:55:48.474 PojavLauncher[2284:542713] EGLBridge: Trigger an initial swapBuffers
2021-03-28 09:55:48.474 PojavLauncher[2284:542713] MGLKViewController pause
2021-03-28 09:55:48.474 PojavLauncher[2284:542713] MGLKViewController resume
2021-03-28 09:55:48.477 PojavLauncher[2284:542713] libGL=0x281465ec0
2021-03-28 09:55:48.480 PojavLauncher[2284:542566] MGLKViewController pause
2021-03-28 09:55:48.487 PojavLauncher[2284:542713] GL4ES init success
[01:55:48] [Thread-1/FATAL] [ne.mi.fm.lo.FMLCommonLaunchHandler/CORE]: Failed to find Minecraft resource version 1.16.5-20210115.111550 at /var/mobile/Documents/minecraft/libraries/net/minecraftforge/forge/1.16.5-36.1.0/forge-1.16.5-36.1.0-client.jar
[01:55:48] [Thread-1/INFO] [STDERR/]: [net.kdt.pojavlaunch.Tools:showError:444]: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Missing minecraft resource!
	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:755)
	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:202)
	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1067)
	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 6 more

2021-03-28 09:56:28.261 PojavLauncher[2284:542566] MGLKViewController pause
2021-03-28 09:56:28.385 PojavLauncher[2284:542566] MGLKViewController pause

**Comment by jammmy2** [comment]
Hello pls someone reply?

**Comment by khanhduytran0** [comment]
Looks like Minecraft was corrupted.

**Comment by khanhduytran0** [comment]
Also, follow the **issue template**

**Comment by jammmy2** [comment]
What do you mean?
