### ISSUE TITLE
Crash when trying to sign in, error when selecting account 

### ISSUE THREAD

**Issue by BobKat4k** [PojavLauncherTeam/PojavLauncher_iOS#130]
Ever since I installed 1.12.2 forge I’ve received this error when selecting my account

java.lang.RuntimeException: Respone error, code: 403, message: {"error":"ForbiddenOperationException","errorMessage":"Token does not exist"}
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:16)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:21)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.refresh(YggdrasilAuthenticator.java:112)
	at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.run(RefreshTokenTask.java:22)
	at net.kdt.pojavlaunch.PojavProfile.updateTokens(PojavProfile.java:63)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:32)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:39)

Crashes when signing in manually

**Comment by BobKat4k** [comment]
I’ve found a fix! Just delete the .pojavlauncher folder and re install it from the .deb, however other comments have said that this fix is only temporary.

**Comment by Doregon** [comment]
You can also swipe left on the account in question to delete the info, and just log in again. Still only temporary :/

**Comment by Xlebyshig** [comment]
I found a solution! go to the new account and click on the upper left corner, and select the account that is with an error

**Comment by santinoabee** [comment]
i cannot to login to my stupid account

**Comment by khanhduytran0** [comment]
> You can also swipe left on the account in question to delete the info, and just log in again. Still only temporary :/

Migrating to Microsoft account should “fix” the invalid token issue.

**Comment by Doregon** [comment]
Closing as the solution is to either use a Microsoft account or delete and re-add the Mojang account.
