### ISSUE TITLE
Stuck on black screen

### ISSUE THREAD

**Issue by StellCapalot** [PojavLauncherTeam/PojavLauncher_iOS#133]
I’m using iOS 14.3 iPhone 11 Pro Max
And running latest version from Sileo 

Instead of loading the game after installing forge I get stuck on this screen
 
![061668CE-E5CC-4F9A-9E63-B2CC65277589](https://user-images.githubusercontent.com/82723878/115121166-3859bc00-9f7f-11eb-816e-651d6db4d736.png)

2021-04-17 13:05:43.027 PojavLauncher[6698:538479] Beginning JVM launch
2021-04-17 13:05:43.027 PojavLauncher[6698:538479] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-04-17 13:05:43.027 PojavLauncher[6698:538479] Reading custom JVM args (overrideargs.txt), opened=0
2021-04-17 13:05:43.028 PojavLauncher[6698:538479] Found JLI lib
2021-04-17 13:05:43.028 PojavLauncher[6698:538479] Calling JLI_Launch
2021-04-17 13:05:43.028 PojavLauncher[6698:538487] Beginning JVM launch
2021-04-17 13:05:43.028 PojavLauncher[6698:538487] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-04-17 13:05:43.028 PojavLauncher[6698:538487] Found JLI lib
2021-04-17 13:05:43.028 PojavLauncher[6698:538487] Calling JLI_Launch
We are on java now! Starting UI...
2021-04-17 13:05:43.096 PojavLauncher[6698:538479] libpojavexec loaded from vm=0x101e12698
Finding a version
Selected Minecraft version: 1.16.5-forge-36.1.4
Downloading version list
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Downloading 1.16.5-forge-36.1.4.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading 1.16.5-forge-36.1.4.jar
2021-04-17 13:05:47.163 PojavLauncher[6698:538479] MGLKViewController viewDidLoad
2021-04-17 13:05:47.164 PojavLauncher[6698:538479] Received SurfaceViewController callback, width=2688, height=1242
Saving GLES context
Launching Minecraft 1.16.5-forge-36.1.4
Library org.apache.logging.log4j:log4j-api: Replaced version 2.8.1 with 2.11.2
Library org.apache.logging.log4j:log4j-core: Replaced version 2.8.1 with 2.11.2
Library net.sf.jopt-simple:jopt-simple: Replaced version 5.0.3 with 5.0.4
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Args init finished. Now starting game
2021-04-17 13:05:47.204 PojavLauncher[6698:538479] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x107285400>)
2021-04-17 17:05:47,515 Thread-1 WARN Advanced terminal features are not available in this environment
[17:05:47] [Thread-1/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Capalot, --version, 1.16.5, --gameDir, /var/mobile/Documents/minecraft, --assetsDir, /var/mobile/Documents/minecraft/assets, --assetIndex, 1.16, --uuid, 0, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.4, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --fullscreen]
[17:05:47] [Thread-1/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 17-ea by Procursus
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x257d08b3) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x257d08b3
	at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
	at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
	at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
	at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
	at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 6 more

2021-04-17 13:05:47.711 PojavLauncher[6698:538479] MGLKViewController viewDidAppear
2021-04-17 13:05:47.711 PojavLauncher[6698:538479] MGLKViewController pause
2021-04-17 13:05:47.711 PojavLauncher[6698:538479] MGLKViewController resume
2021-04-17 13:05:47.727 PojavLauncher[6698:538479] MGLKViewController pause
2021-04-17 13:06:16.074 PojavLauncher[6698:538479] MGLKViewController pause
2021-04-17 13:06:16.147 PojavLauncher[6698:538479] MGLKViewController pause

**Comment by khanhduytran0** [comment]
Why Java 17?

**Comment by Diatrus** [comment]
@khanhduytran0 Procursus currently uses an early version of Java 17, close to the final version of Java 16.

**Comment by khanhduytran0** [comment]
> @khanhduytran0 Procursus currently uses an early version of Java 17, close to the final version of Java 16. 

Can you change back to java 16? As you see Forge 1.16.5 is broken in java 17 due to internal classes restrictions...

**Comment by khanhduytran0** [comment]
I mean this change https://github.com/ProcursusTeam/Procursus/commit/f11ed2240aaabe4f3e25325ba87e892cacc37c3d#diff-e4b86cf35fcb7d251617eb592e38cf8fed6191be4e9b1da099ed885ad389132b

**Comment by StellCapalot** [comment]
I downgraded PojavLauncher to 1.0 and it fixed it but idk it that would be the main solution

**Comment by Diatrus** [comment]
> > @khanhduytran0 Procursus currently uses an early version of Java 17, close to the final version of Java 16.
> 
> Can you change back to java 16? As you see Forge 1.16.5 is broken in java 17 due to internal classes restrictions...

I can. Give me a day.

**Comment by Doregon** [comment]
@StellCapalot, @Diatrus made a change to PojavLauncher on Procursus. It's updated to the latest commit on main and rolls back to openjdk-16-jre. Reinstall PojavLauncher and that should fix Forge.

**Comment by Doregon** [comment]
Issue fixed with @Diatrus’ change and update to 1.2
