### ISSUE TITLE
[Bug Report] stuck on “saving world screen”

### ISSUE THREAD

**Issue by imafatboy** [PojavLauncherTeam/PojavLauncher_iOS#161]
// Delete this line and the above text before submitting.

**First, let us know what you’re using.**
Tell us what iOS/iPadOS device and version you’re using, and the PojavLauncher version.
iPhone SE iOS 14.1 v1.2
**Next, describe the issue.**
Make sure to be as descriptive as possible. 
Using Fabric from doregons repo logging into a world it gets stuck onto “saving world” although when I switch to optifine or vanilla it works fine.
**What’s supposed to happen?**
What were you expecting? To get into my world 

**How does it happen?**
Let’s get a step by step on how to reproduce this issue.
When select any world or create an new one it gets stuck on “saving world” 
**Any files you want to send?**
We could use a copy of latestlog.txt or a Cr4shed screenshot.

[22:53:22] [Thread-1/INFO]: Loading for game Minecraft 1.16.5
[22:53:23] [ForkJoinPool-1-worker-11/WARN]: Non-Fabric mod JAR at "/var/mobile/Documents/minecraft/mods/cgm-1.0.1-1.16.3.jar", ignoring
[22:53:23] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:53:23] [ForkJoinPool-1-worker-7/WARN]: Non-Fabric mod JAR at "/var/mobile/Documents/minecraft/mods/Xaeros_Minimap_21.7.1_Forge_1.16.5.jar", ignoring
[22:53:23] [ForkJoinPool-1-worker-11/WARN]: Non-Fabric mod JAR at "/var/mobile/Documents/minecraft/mods/OptiFine_1.16.5_HD_U_G7.jar", ignoring
[22:53:23] [Thread-1/WARN]: Warnings were found! 
 - Mod 'AntiGhost' (antighost) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
[22:53:23] [Thread-1/INFO]: [FabricLoader] Loading 104 mods: fabric-keybindings-v0@0.2.1+ca58154a7d, notenoughcrashes@3.1.8, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, crowdin-translate@1.2, artifice@0.14.6+1.16.5, hydrogen@0.2-SNAPSHOT, fabric-dimensions-v1@2.0.6+9354966b7d, java@16, betternether@5.0.7, cotton-client-commands@1.0.1+1.16-rc1, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, jumploader@2.1.3, fiber@0.23.0-2, lambdynlights@1.3.4+1.16, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, com_moandjiezana_toml_toml4j@0.7.2, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric@0.32.0+1.16, fabric-networking-v0@0.3.2+ca58154a7d, org_codehaus_groovy_groovy@3.0.3, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, tk_valoeghese_zoesteriaconfig@1.3.2, repurposed_structures@1.16.5-1.10.4-fabric, modmenu@1.16.8, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, angerable-patch@1.1.0-1.16.4, cloth-client-events-v0@1.5.47, enchant_giver@1.0.3, voyager@1.0.0, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, mostructures@1.1.1+mc.1.16.5, fabric-language-kotlin@1.5.0+kotlin.1.4.31, fabric-key-binding-api-v1@1.0.4+9354966b7d, cloth-config2@4.11.14, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, malilib@0.10.0-dev.21+arne.2, org_jetbrains_kotlin_kotlin-reflect@1.4.31, antighost@1.16.5-fabric0.30.0-1.1.3, architectury@1.8.130, colormatic@2.2.8+mc.1.16.3, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, krypton@0.1.2, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-structure-api-v1@1.1.4+ca58154a7d, org_aperlambda_lambdajcommon@1.8.1, fabric-containers-v0@0.1.11+9354966b7d, lithium@0.6.4, fabric-object-builder-api-v1@1.9.4+9354966b7d, mcdw@3.1.2, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, mcda@1.4.2, mm@2.1, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, lazydfu@0.1.2, raisedclouds@1.0.0, starlight@0.0.3, reach-entity-attributes@1.0.1, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, sodium@0.1.1-SNAPSHOT, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, nofade@1.16.5-1.0.1, fastchest@1.2+1.16, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, okzoomer@4.0.1+1.16.2, custom-fog@1.4.0, fabric-command-api-v1@1.1.0+f9b3753b7d, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, smoothboot@1.16.5-1.5.0, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, slight-gui-modifications@1.7.1, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, spruceui@2.0.4+1.16, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, indium@1.0.0, fabric-biome-api-v1@3.1.1+ca58154a7d, ferritecore@2.0.2, byg@1.1.7, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, org_codehaus_groovy_groovy-jsr223@3.0.3, fabric-object-builders-v0@0.7.2+ca58154a7d
[22:53:23] [Thread-1/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/var/mobile/Documents/minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[22:53:23] [Thread-1/INFO]: Loaded configuration file for Sodium: 24 options available, 0 override(s) found
[22:53:23] [Thread-1/INFO]: Loaded configuration file for Lithium: 80 options available, 1 override(s) found
[22:53:24] [Thread-1/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[22:53:24] [Thread-1/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.BakedQuadAccess is disabled as Hydrogen is installed
[22:53:24] [Thread-1/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.SimpleModelBuilderMixin is disabled as Hydrogen is installed
[22:53:24] [Thread-1/WARN]: @Mixin target net/minecraft/class_4970$class_4971$class_3752 is public in ferritecore.blockstatecache.mixin.json:BlockStateCacheAccess and should be specified in value
[22:53:24] [Thread-1/WARN]: Mixin malte0811.ferritecore.mixin.fastmap.FastMapStateHolderMixin is disabled as Hydrogen is installed
[22:53:24] [Thread-1/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[22:53:24] [Thread-1/WARN]: Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
[22:53:24] [Thread-1/WARN]: ** The JVM might warn you with something nasty! **
[22:53:24] [Thread-1/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/var/mobile/Documents/minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[22:53:24] [Thread-1/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/var/mobile/Documents/minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[22:53:24] [Thread-1/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/var/mobile/Documents/minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySet.class)
[22:53:24] [Thread-1/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/var/mobile/Documents/minecraft/mods/hydrogen-fabric-mc1.16.5-0.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[22:53:24] [Thread-1/INFO]: Smooth Boot config initialized
[22:53:28] [Thread-1/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:53:28] [Thread-1/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:625) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:409) ~[intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[fabric-loader-0.11.3-1.16.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129) ~[launcher.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:53:28] [Thread-1/INFO]: Setting user: Im a Fag
[22:53:28] [Thread-1/INFO]: Initializing StacktraceDeobfuscator
[22:53:28] [Thread-1/INFO]: Done initializing StacktraceDeobfuscator
[22:53:31] [Thread-1/INFO]: [Enchant Giver] has been initiated.
[22:53:31] [Thread-1/INFO]: Compression will use Java 11, encryption will use Java
[22:53:31] [Thread-1/INFO]: Definitely not up to no good
[22:53:31] [Thread-1/INFO]: NoFadeIn is running
[22:53:31] [Thread-1/INFO]: BYG: Blocks registered!
[22:53:31] [Thread-1/INFO]: BYG: Items registered!
[22:53:31] [Thread-1/ERROR]: No data fixer registered for byg:boat
[22:53:31] [Thread-1/INFO]: BYG: Entities registered!
[22:53:32] [Thread-1/INFO]: BYG: Biomes registered!
[22:53:32] [Thread-1/INFO]: BYG: Decorators registered!
[22:53:32] [Thread-1/INFO]: BYG: Features registered!
[22:53:32] [Thread-1/INFO]: BYG: Surface builders Registered!
[22:53:32] [Thread-1/INFO]: BYG: Registering block placer types!
[22:53:32] [Thread-1/INFO]: Reading Sub-Biomes json
[22:53:32] [Thread-1/INFO]: Reading json
[22:53:32] [Thread-1/INFO]: Adding Numerical Biome ID's
[22:53:32] [Thread-1/INFO]: Added Numerical Biome ID's!
[22:53:32] [Thread-1/INFO]: BYG: "Common Setup" Event Complete!
[22:53:32] [Thread-1/INFO]: BYG: Compostible Blocks Added!
[22:53:32] [Thread-1/INFO]: BYG: Added Hoeable Blocks!
[22:53:32] [Thread-1/INFO]: BYG: Added Flammables!
[22:53:32] [Thread-1/INFO]: BYG: Added strippable Blocks...
[22:53:32] [Thread-1/INFO]: BYG: "Load Complete" Event Complete!
[22:53:32] [Thread-1/INFO]: [LambDynLights] Initializing LambDynamicLights...
[22:53:32] [Thread-1/INFO]: [LambDynLights] Configuration loaded.
[22:53:32] [Thread-1/WARN]: WARNING! Mod crowdin-translate is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod artifice is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cotton-client-commands is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cotton-client-commands is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod fiber is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cloth-client-events-v0 is only using deprecated 'modmenu:parent' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cloth-client-events-v0 is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cloth-client-events-v0 is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod fabric-language-kotlin is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cloth-config2 is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod malilib is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod architectury is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod mm is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod reach-entity-attributes is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod spruceui is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/WARN]: WARNING! Mod autoconfig1u is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[22:53:32] [Thread-1/INFO]: Krypton is now accelerating your Minecraft client's networking stack 🚀
[22:53:32] [Thread-1/INFO]: Note that Krypton is most effective on servers, not the client.
[22:53:32] [Thread-1/INFO]: [Custom Fog] Initializing
[22:53:32] [Thread-1/INFO]: [Custom Fog] Loading config file
[22:53:32] [Thread-1/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[22:53:32] [ForkJoinPool.commonPool-worker-3/INFO]: Start Loading of CTS.
[22:53:32] [Thread-1/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[22:53:33] [Thread-1/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/var/mobile/Documents/minecraft/resourcepacks/BSL_v8.0.01.zip'
[22:53:33] [Thread-1/WARN]: Couldn't get pack info for: net.minecraft.class_3266: 'pack.mcmeta' in ResourcePack '/var/mobile/Documents/minecraft/resourcepacks/BSL_v8.0.01 (1).zip'
[22:53:34] [Thread-1/INFO]: Reloading ResourceManager: Default, Programmer Art (Mod Menu), Clarity-1.16.zip, Fabric Mods (Fabric Key Bindings (v0), Not Enough Crashes, Fabric Loader, Artifice, Hydrogen, Better Nether, Fabric Game Rule API (v1), Fabric API Base, Jumploader, LambDynamicLights, Fabric BlockRenderLayer Registration (v1), Fabric API, Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Screen Handler API (v1), Repurposed Structures, Mod Menu, Fabric Tool Attribute API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Mo' Structures, Fabric Language Kotlin, Fabric Key Binding API (v1), Cloth Config v4, Fabric Resource Loader (v0), MaLiLib, AntiGhost, Colormatic, Fabric Registry Sync (v0), Fabric Commands (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Krypton, Fabric Models (v0), Fabric Item Groups (v0), Fabric Renderer API (v1), Fabric Structure API (v1), Fabric Containers (v0), Lithium, Fabric Object Builder API (v1), MC Dungeons Weapons, Fabric Rendering Data Attachment (v1), MC Dungeons Armors, Manningham Mills, Fabric Textures (v0), Fabric Rendering Fluids (v1), LazyDFU, Raised Clouds, Reach Entity Attribute, Fabric Lifecycle Events (v1), Sodium, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Particles (v1), No Fade, FastChest, Fabric Networking Block Entity (v0), Ok Zoomer, Custom Fog, Fabric Command API (v1), Fabric Screen API (v1), Fabric Renderer - Indigo, Smooth Boot, Fabric Item API (v1), Fabric Entity Events (v1), 'Slight' GUI Modifications, Fabric Rendering (v0), Fabric Rendering (v1), SpruceUI, Auto Config v1 Updated, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), BYG, Fabric Events Lifecycle (v0), Fabric Object Builders (v0)), Generated Resources
[22:53:34] [Thread-1/INFO]: [STDOUT]: Inject generated resource packs.
[22:53:42] [Thread-1/INFO]: OpenAL initialized.
[22:53:42] [Thread-1/INFO]: Sound engine started
[22:53:42] [Thread-1/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 2048x2048x4 minecraft:textures/atlas/blocks.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 512x512x4 minecraft:textures/atlas/chest.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 1024x512x4 minecraft:textures/atlas/beds.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:53:42] [Thread-1/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:53:44] [Thread-1/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[22:53:44] [Thread-1/INFO]: Created: 512x512x0 minecraft:textures/atlas/paintings.png-atlas
[22:53:44] [Thread-1/INFO]: Created: 512x256x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:53:44] [Thread-1/INFO]: [[[ Deduplication statistics ]]]
[22:53:44] [Thread-1/INFO]: Baked quad cache: DeduplicationCache ( 65311 de-duplicated, 238659 entries )
[22:53:45] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[22:53:46] [Thread-1/WARN]: Warning! Mod angerable-patch has a broken icon, loading default icon
[22:54:20] [Thread-1/WARN]: Warning! Mod enchant_giver has a broken icon, loading default icon
[22:54:20] [Thread-1/WARN]: Warning! Mod ferritecore has a broken icon, loading default icon
[22:54:20] [Thread-1/WARN]: Warning! Mod indium has a broken icon, loading default icon
[22:54:49] [Thread-1/WARN]: Warning! Mod raisedclouds has a broken icon, loading default icon
[22:54:52] [Thread-1/WARN]: Warning! Mod starlight has a broken icon, loading default icon
[22:54:52] [Thread-1/WARN]: Warning! Mod voyager has a broken icon, loading default icon
[22:55:23] [Thread-1/WARN]: Warning! Mod angerable-patch has a broken icon, loading default icon

**Comment by Doregon** [comment]
PojavFabric is not an official PLT project and I have *deprecated it*. I would recommend manually installing Fabric for the time being.

**Comment by imafatboy** [comment]
Forgot to add that it was working before but I’ll try to do it manually and see if that works

**Comment by Doregon** [comment]
If it was working before, check the permissions on the minecraft and .pojavlauncher folders in Filza.

**Comment by imafatboy** [comment]
Ok I’ve reinstalled it from the repo because I was having trouble doing it manually and now when I configure the version to fabric it crashes when the ui shows up, but it works perfectly when switching it to optifine

**Comment by Doregon** [comment]
Run these and try again (if you don’t have sudo, use su and then run it without sudo.):

sudo chown -R mobile:mobile /var/mobile/Documents/{.pojavlauncher,minecraft}
sudo chmod -R 755 /var/mobile/Documents/{.pojavlauncher,minecraft}

**Comment by imafatboy** [comment]
Ok after running the commands and removing all mods from the mods folder and then reinstalling projavoptimize and fabric from repo it worked again, thank you!
