### ISSUE TITLE
[Bug] <Help>

### ISSUE THREAD

**Issue by SailentWasTaken** [PojavLauncherTeam/PojavLauncher_iOS#256]
### Describe the bug

I’ve installed forge so I wanted to run it but it’s just glitched so I needed to remove the mods. I ended deleting all the files and now I’ve re installed and get this issue. java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3308)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3449)
	at java.base/java.lang.Class.getMethod0(Class.java:3435)
	at java.base/java.lang.Class.getMethod(Class.java:2194)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:141)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 7 more

### Steps To Reproduce

```markdown
Delete all the files in the Minecraft folder and then re install PojavLauncher through Filza
```

### Expected Behavior

I expected the game to run normally

### Platform

```markdown
- Device model: iPad 6th Generation
- iOS version: 14.3
- PojavLauncher version: Latest 1.3
```

**Comment by khanhduytran0** [comment]
Try a clean re-install.

**Comment by khanhduytran0** [comment]
Is this related to #257 and 258? @SailentWasTaken

**Comment by Doregon** [comment]
Closing stale issue.
