### ISSUE TITLE
[Bug] Unable to login with Microsoft

### ISSUE THREAD

**Issue by NoDa75** [PojavLauncherTeam/PojavLauncher_iOS#261]
### Describe the bug

When I login with Microsoft on PojavLauncher Dev, it says unable to login, and says “java.lang.RuntimeException: MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:38)

### Steps To Reproduce

```markdown
Login with Microsoft
Allow launcher to use account
```

### Expected Behavior

Login to the launcher with my Microsoft account and play Minecraft

### Platform

```markdown
- Device model: iPhone SE (2020)
- iOS version: 14.2
- PojavLauncher version: DEV 1.3-alpha80
```

**Comment by Pan00Pernicek** [comment]
if your account is below 18 years old, it wont work iirc

**Comment by Doregon** [comment]
You need to either create a new Microsoft account and add this account to a Family, or change your account's age to 18 or above.

**Comment by asdfugil** [comment]
How does that make this not an issue

**Comment by Doregon** [comment]
Meant to just comment

**Comment by Doregon** [comment]
Closing this as it has been moved to the known issues list.

**Comment by Johnmatthewberecio** [comment]
Why i cannot login in microsoft on Pojavlauncher
, It will say unable to login and say
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:231)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by GaucovyAero** [comment]
log into minecraft.net and set up your minecraft account
