### ISSUE TITLE
[Bug] Fabric Loader 0.12.11-1.16.5 not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#297]
### Describe the bug

Not opening

### The log file and images/videos

![FF8BB45E-0F1E-4E06-A44A-CE8BE0B84E66](https://user-images.githubusercontent.com/45666011/145707926-f33f9328-19cc-4e54-81d4-f20b6c67d320.png)

Latestlog file:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7698981/latestlog.txt)

Full here:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:209)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 6 more

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Select Local Account
3. Select Fabric
4. See the error

(I deleted all the files and folders in the PojavLauncher directory and downloaded all the files and folders again and I runned Fabric Installer again and install it again, but it still doesn't work)
```

### Expected Behavior

Opened game

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 14.5.1
- PojavLauncher version: Latest Pre-Release dev channel
```

### Anything else?

/

**Comment by khanhduytran0** [comment]
Account type is not stated. Also lack of latestlog.txt

**Comment by admin-elvistrujanovic** [comment]
> Account type is not stated. Also lacks of latestlog.txt

☝️

**Comment by Doregon** [comment]
> [15:09:35] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.

You didn't reinstall the vanilla copy of 1.16.5. We also do not provide support for local mode issues.
