### ISSUE TITLE
[Bug] fabric-loader-0.12.12-1.18.1 causes error on start

### ISSUE THREAD

**Issue by Lilyp3892** [PojavLauncherTeam/PojavLauncher_iOS#304]
### Describe the bug

Running fabric-loader-0.12.12-1.18.1 causes error. The controls come up and then then it sends up a crash report on the screen. I’ve uninstalled and reinstalled it many times

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/7797417/latestlog.txt)

### Steps To Reproduce

```markdown
1. Download fabric.jar from the official fabric site
2. Start pojavlauncher
3. Login to your account
4. Click the ...
5. Click preferences
6. Select Java 8 and restart pojavlauncher
7. Open pojavlauncher
8. Login and open mod installer
9. Select the downloaded .jar for fabric
10. Proceed to install fabric for 1.18.1
11. Restart pojavlauncher
12. login
13. Change Java version to 17
14. Restart pojavlauncher
15. Login
16. Select fabric-loader-0.12.12-1.18.1
17. Hit play
18. See error message
```

### Expected Behavior

I expected the game to continue after step 17 to loading up completely like I have successfully done with 1.18.1-OptiFine_HD_U_H4

### Platform

```markdown
- Device model: IPhone XR
- iOS version: 14.3
- PojavLauncher version: version 2.0
```

### Anything else?

I’m not sure why I’m able to run optifine just fine using the same steps (the only difference being I downloaded the optifine installer instead of the fabric one) thank you to anyone who can help

Edit: I am using an online account

**Comment by khanhduytran0** [comment]
You didn't explicitly state if you've logged in with an online account (required in 15th step)

**Comment by Lilyp3892** [comment]
I did login with an online account my bad

**Comment by Doregon** [comment]
```
[06:04:45] [ERROR] [FabricLoader/GameProvider]: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
```

Did you install vanilla 1.18.1 before attempting to launch Fabric?

**Comment by khanhduytran0** [comment]
> Did you install vanilla 1.18.1 before attempting to launch Fabric?

I reproduced it, it failed to locate the game somehow.
So I got a workaround: add `-Dfabric.gameJarPath=/usr/share/pojavlauncher/instances/default/minecraft/versions/fabric-loader-0.12.12-1.18.1/fabric-loader-0.12.12-1.18.1.jar` to JVM arguments.

**Comment by admin-elvistrujanovic** [comment]
> > Did you install vanilla 1.18.1 before attempting to launch Fabric?
> 
> 
> 
> I reproduced it, it failed to locate the game somehow.
> 
> So I got a workaround: add `-Dfabric.gameJarPath=/usr/share/pojavlauncher/instances/default/minecraft/versions/fabric-loader-0.12.12-1.18.1/fabric-loader-0.12.12-1.18.1.jar` to JVM arguments.

I have the same problem but when I run this in JVM args I get this:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:162)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Game jar /usr/share/pojavlauncher/instances/default/minecraft/versions/fabric-loader-0.12.12-1.18.1/fabric-loader-0.12.12-1.18.1.jar configured through fabric.gameJarPath system property doesn't exist
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:172)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 6 more

And I have installed Fabric 1.12.2 for MC 1.18.1 sucessfully with vanila 1.18.1 - using an online account
