### ISSUE TITLE
[Bug] Microsoft Sign In Error 

### ISSUE THREAD

**Issue by popbobb** [PojavLauncherTeam/PojavLauncher_iOS#310]
### Describe the bug

Logging in with Microsoft throws a error.

### The log file and images/videos

java.lang.RuntimeException: MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:44)

### Steps To Reproduce

```markdown
Start PojavLauncher and login with Microsoft.
```

### Expected Behavior

I expected it to log me in.

### Platform

```markdown
- Device model: 
- iOS version: 
- PojavLauncher version:
```

**Comment by Doregon** [comment]
#184
