### ISSUE TITLE
[Bug] <Short description>i cant start the game

### ISSUE THREAD

**Issue by ckbso19** [PojavLauncherTeam/PojavLauncher_iOS#342]
### Describe the bug

cannot launch fabric-1.16.5 

### The log file and images/videos

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:209)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 6 more

==========================================================================
when i try to launch pojavoptimize1.16.5
java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.knot.KnotClient
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:143)
	at java.base/java.lang.Thread.run(Thread.java:831)

### Steps To Reproduce

```markdown
1.start pojavlauncher and select the accounts
2.change version to fabric-loader-0.13.3-1.16.5(installed with latest fabric installer)
3.cannot launch the game but the gui can display normally
```

### Expected Behavior

the game to launch

### Platform

```markdown
- Device model: iphone11 promax
- iOS version: 14.8
- PojavLauncher version: 2.0.1
```

**Comment by khanhduytran0** [comment]
If you used local account, it wouldn’t work.
Try logging in with a Microsoft account to play.

**Comment by ckbso19** [comment]
The problem remains
==============================================================
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:145)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:209)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:125)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
... 6 more

**Comment by crystall1nedev** [comment]
You need to install the base game before you can launch Fabric. Select 1.16.5 in the version list and launch it. If you're using a local account, you cannot install.
