### ISSUE TITLE
[Bug] Can’t use openjdk 17

### ISSUE THREAD

**Issue by Prvateturtle** [PojavLauncherTeam/PojavLauncher_iOS#352]
### Describe the bug

When I install the openjdk 17 on cydia and open pojav launcher app and select java 17 and restart the app it’s keeps on crashing and I can’t open the app until I delete it

### Steps To Reproduce

```markdown
When i select java 17 and restart the game
```

### Expected Behavior

It would work and I would be able to play 1.17-1.19

### Platform

```markdown
- Device model:iPhone 6s 
- iOS version:12.4.1 
- PojavLauncher version: 2.0.1
```

**Comment by crystall1nedev** [comment]
We can't help without logs.

**Comment by Prvateturtle** [comment]
@crystall1nedev here java.lang.UnsupportedOperationException: Minecraft 1.19.1 requires Java 17 in order to run. Please switch to Java 17 in launcher settings.
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:94)
	at net.kdt.pojavlaunch.PLaunchApp.launchMinecraft(PLaunchApp.java:47)
	at net.kdt.pojavlaunch.uikit.UIKit.callback_SurfaceViewController_launchMinecraft(UIKit.java:104)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:40)

**Comment by Prvateturtle** [comment]
I selected 17 java but then selected 1.19.1 but it crashed and just keeps on crashing

**Comment by Prvateturtle** [comment]
I selected 17 java but then selected 1.19.1 but it crashed and just keeps on crashing

**Comment by khanhduytran0** [comment]
You need the latest dev build in order for 1.19+ to work. Also, you need to re-download the assets after updating.

**Comment by Prvateturtle** [comment]
@khanhduytran0 I can’t install the newest dev build

**Comment by crystall1nedev** [comment]
Closing issue due to inactivity, make sure to update to the latest build for 1.19 support.
