### ISSUE TITLE
[Bug] Black screen on version launch

### ISSUE THREAD

**Issue by ahoss10** [PojavLauncherTeam/PojavLauncher_iOS#357]
### Describe the bug

Cannot launch 1.19 or 1.19 optifine

### The log file and images/videos

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/6/22, 2:55 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: /private/var/mobile/Containers/Data/Application/5EACB5F9-9E8B-4986-969C-91EA167B1C8E/tmp/libjcocoa16166047886632923407.dylib: dlopen(/private/var/mobile/Containers/Data/Application/5EACB5F9-9E8B-4986-969C-91EA167B1C8E/tmp/libjcocoa16166047886632923407.dylib, 1): no suitable image found.  Did find:
	/private/var/mobile/Containers/Data/Application/5EACB5F9-9E8B-4986-969C-91EA167B1C8E/tmp/libjcocoa16166047886632923407.dylib: mach-o, but not built for platform iOS
	/private/var/mobile/Containers/Data/Application/5EACB5F9-9E8B-4986-969C-91EA167B1C8E/tmp/libjcocoa16166047886632923407.dylib: mach-o, but not built for platform iOS
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at ca.weblite.nativeutils.NativeUtils.loadLibraryFromJar(NativeUtils.java:55)
	at ca.weblite.nativeutils.NativeUtils.loadLibraryFromJar(NativeUtils.java:38)
	at ca.weblite.objc.RuntimeUtils.<clinit>(RuntimeUtils.java:59)
	at ca.weblite.objc.Client.sendProxy(Client.java:381)
	at dyp.a(SourceFile:42)
	at eev.<init>(SourceFile:474)
	at net.minecraft.client.main.Main.main(SourceFile:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:79)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:43)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at ca.weblite.nativeutils.NativeUtils.loadLibraryFromJar(NativeUtils.java:55)
	at ca.weblite.nativeutils.NativeUtils.loadLibraryFromJar(NativeUtils.java:38)
	at ca.weblite.objc.RuntimeUtils.<clinit>(RuntimeUtils.java:59)
	at ca.weblite.objc.Client.sendProxy(Client.java:381)
	at dyp.a(SourceFile:42)
	at eev.<init>(SourceFile:474)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:79)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:43)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (aarch64) version 14.3
	Java Version: 17-ea, Procursus
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Procursus
	Memory: 318950800 bytes (304 MiB) / 939524096 bytes (896 MiB) up to 939524096 bytes (896 MiB)
	CPUs: 6
	Processor Vendor: 
	Processor Name: 
	Identifier:  Family  Model  Stepping 
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 2973.66
	Virtual memory used (MB): 2039.56
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms892M -Xmx892M
	Launched Version: 1.19
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.19_HD_U_H9
	OptiFine Build: 20220731-224510
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 6

### Steps To Reproduce

```markdown
1. Start launcher
2. Preferences / tinygl4 / java 17
```

### Expected Behavior

1. Launch the game

### Platform

```markdown
- Device model: iPhone 8+
- iOS version: 14.3
- PojavLauncher version: 2.1b43
```

**Comment by khanhduytran0** [comment]
You must delete the icon asset file in order to workaround this crash. Finding it is not an easy task for you, so delete the assets folder then try again.
