### ISSUE TITLE
[Bug] Crash launching fabric 1.16.5

### ISSUE THREAD

**Issue by LolekLiam** [PojavLauncherTeam/PojavLauncher_iOS#401]
### Describe the bug

Clicking play on fabric loader 1.16.5 results in crash

### The log file and images/videos

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:145)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:214)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 6 more

### Steps To Reproduce

```markdown
1. Open Pojavlauncher
2. Select version fabric-loader-0.14.9-1.16.5
3. Press play
```

### Expected Behavior

Normal game launch expected

### Platform

```markdown
- Device model: iPad Pro (9.7-inch)
- iOS version: 14.4.2
- PojavLauncher version: 2.0.1
```

**Comment by khanhduytran0** [comment]
This was fixed in https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/e5018cc (ignore the commit message)
Please update to the latest dev build.

**Comment by LolekLiam** [comment]
> This was fixed in [e5018cc](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/commit/e5018cc) (ignore the commit message)
> Please update to the latest dev build.

I cant via Cydia it throws me an error:

Downloading PojavLauncher iOS (Development)
Done PojavLauncher iOS (Development)
Running Debian Packager
dpkg-deb —control subprocess returned error exit status 2
Sub-process /usr/libexec/cydia/cydo returned an error code (1)

**Comment by LolekLiam** [comment]
installing ipa also throws an error:

Rejecting downgrade of system/internal app net.kdt.pojavlauncher: installed version is 2, proposed version is 2

**Comment by khanhduytran0** [comment]
> installing ipa also throws an error:
> 
> Rejecting downgrade of system/internal app net.kdt.pojavlauncher: installed version is 2, proposed version is 2

You need to uninstall PojavLauncher deb before sideloading ipa. Additionally, use TrollStore instead to sideload.

**Comment by LolekLiam** [comment]
> > installing ipa also throws an error:
> > Rejecting downgrade of system/internal app net.kdt.pojavlauncher: installed version is 2, proposed version is 2
> 
> You need to uninstall PojavLauncher deb before sideloading ipa. Additionally, use TrollStore instead to sideload.

The problem is...it is uninstalled...cydia doesn't detect it and its not on the home screen...

**Comment by LolekLiam** [comment]
i continue this on #404
