### ISSUE TITLE
Error/crash on jailbroken iOS 12.4.8 after logging in with Mojang account

### ISSUE THREAD

**Issue by timof121** [PojavLauncherTeam/PojavLauncher_iOS#42]
So, i downloaded the latest (and first) release. First i installed openjdk via filza, then pojavlauncher also using filza and then runned uicache. When i open pojavlauncher, i try to login with mojang acount, then after putting my account credentials it just crashes. If i login with offline, everything works ok. Please let me know if you need more info.

**Comment by timof121** [comment]
Now it doesnt crash, but gives me thiz error: `java.lang.RuntimeException: Respone error, code: 403, message: {"error":"ForbiddenOperationException","errorMessage":"Forbidden"}
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:16)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:21)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.authenticate(YggdrasilAuthenticator.java:100)
	at net.kdt.pojavlaunch.authenticator.mojang.LoginTask.run(LoginTask.java:19)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:39)
`

**Comment by khanhduytran0** [comment]
It's known issue.
> Login with Mojang (might not work)

I will take a look then...

**Comment by timof121** [comment]
It got fixed for me in a new build, but now i have another issue...
