### ISSUE TITLE
[Bug] Fabric 1.19.2 crash on launch

### ISSUE THREAD

**Issue by MinhKhoa1801** [PojavLauncherTeam/PojavLauncher_iOS#452]
### Describe the bug

Opening the game show a black screen then crash

### The log file and images/videos

2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-Init] PojavLauncher version: release, branch: main, commit: 78c4a6d
2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-Init] iPhone9,3 with iOS 15.7.1 (Unjailbroken)
2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-init] Entitlements availability:
2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-Init] - com.apple.developer.kernel.extended-virtual-addressing: NO
2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-Init] - com.apple.developer.kernel.increased-memory-limit: NO
2022-12-15 13:42:59.289 PojavLauncher[1147:32464] [Pre-Init] - com.apple.private.security.no-sandbox: NO
2022-12-15 13:42:59.290 PojavLauncher[1147:32464] [Pre-Init] - dynamic-codesigning: NO
2022-12-15 13:42:59.815 PojavLauncher[1147:32464] [Pre-init] Restored preference: MULTI_DIR is set to default
2022-12-15 13:42:59.929 PojavLauncher[1147:32464] LauncherPreferences: Unknown key ram_unjb_warn
2022-12-15 13:42:59.929 PojavLauncher[1147:32464] [Pre-init] LauncherPreferences: ram_unjb_warn is NULL
2022-12-15 13:42:59.938 PojavLauncher[1147:32464] <UIImage:0x282375320 named(main: AppLogo-Vector) {3955, 4400} renderingMode=automatic>
2022-12-15 13:42:59.938 PojavLauncher[1147:32464] <UIImage:0x282375320 named(main: AppLogo-Vector) {3955, 4400} renderingMode=automatic>
2022-12-15 13:42:59.938 PojavLauncher[1147:32464] <UIImage:0x282375320 named(main: AppLogo-Vector) {3955, 4400} renderingMode=automatic>
2022-12-15 13:42:59.938 PojavLauncher[1147:32464] <UIImage:0x282375320 named(main: AppLogo-Vector) {3955, 4400} renderingMode=automatic>
2022-12-15 13:42:59.938 PojavLauncher[1147:32464] <UIImage:0x282375320 named(main: AppLogo-Vector) {3955, 4400} renderingMode=automatic>
2022-12-15 13:42:59.974 PojavLauncher[1147:32464] Debug log not enabled.
2022-12-15 13:43:01.296 PojavLauncher[1147:32464] Found JitStreamer 0.2.0
2022-12-15 13:43:04.474 PojavLauncher[1147:32464] Path is file:///var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/latestlog.old.txt
2022-12-15 13:43:12.759 PojavLauncher[1147:32464] Error?: (null)
Discovering servers...
Stopped discovering servers.
Discovering servers...
2022-12-15 13:45:13.192 PojavLauncher[1147:32464] [MCDL] insertSafety: how to insert assetIndex?
2022-12-15 13:45:13.192 PojavLauncher[1147:32464] [MCDL] insertSafety: how to insert assets?
2022-12-15 13:45:13.221 PojavLauncher[1147:32464] [MCDL] Begin: download libraries
2022-12-15 13:45:13.221 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1
2022-12-15 13:45:13.221 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows-x86
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-linux
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows-x86
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-linux
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1
2022-12-15 13:45:13.222 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows-x86
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-linux
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1
2022-12-15 13:45:13.223 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:tiny-mappings-parser:0.3.0+build.17, attempting to generate one
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows
2022-12-15 13:45:13.223 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:sponge-mixin:0.11.4+mixin.0.8.5, attempting to generate one
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows-x86
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-linux
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos
2022-12-15 13:45:13.223 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:tiny-remapper:0.8.2, attempting to generate one
2022-12-15 13:45:13.223 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows
2022-12-15 13:45:13.224 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:access-widener:2.1.0, attempting to generate one
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows-x86
2022-12-15 13:45:13.224 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for org.ow2.asm:asm:9.3, attempting to generate one
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-linux
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos
2022-12-15 13:45:13.224 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows
2022-12-15 13:45:13.225 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for org.ow2.asm:asm-analysis:9.3, attempting to generate one
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows-x86
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-linux
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1
2022-12-15 13:45:13.225 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows
2022-12-15 13:45:13.225 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for org.ow2.asm:asm-commons:9.3, attempting to generate one
2022-12-15 13:45:13.226 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-x86
2022-12-15 13:45:13.226 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-linux
2022-12-15 13:45:13.226 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos
2022-12-15 13:45:13.226 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for org.ow2.asm:asm-tree:9.3, attempting to generate one
2022-12-15 13:45:13.226 PojavLauncher[1147:32464] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos-arm64
2022-12-15 13:45:13.226 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for org.ow2.asm:asm-util:9.3, attempting to generate one
2022-12-15 13:45:13.226 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:intermediary:1.19.2, attempting to generate one
2022-12-15 13:45:13.227 PojavLauncher[1147:33658] [MCDL] Unknown artifact object for net.fabricmc:fabric-loader:0.14.11, attempting to generate one
2022-12-15 13:45:13.234 PojavLauncher[1147:32464] [MCDL] Finished: download libraries
2022-12-15 13:45:13.234 PojavLauncher[1147:32464] [MCDL] Begin: download assets
2022-12-15 13:45:21.021 PojavLauncher[1147:32464] [MCDL] Finished: download assets
2022-12-15 13:45:21.368 PojavLauncher[1147:32484] [MCDL] insertSafety: how to insert assetIndex?
2022-12-15 13:45:21.368 PojavLauncher[1147:32484] [MCDL] insertSafety: how to insert assets?
2022-12-15 13:45:21.380 PojavLauncher[1147:32484] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2022-12-15 13:45:21.380 PojavLauncher[1147:32484] [JavaLauncher] Beginning JVM launch
2022-12-15 13:45:21.380 PojavLauncher[1147:32484] [JavaLauncher] Attempting to change to Java 17 (actual might be higher)
2022-12-15 13:45:21.383 PojavLauncher[1147:32484] [JavaLauncher] JAVA_HOME is now set to /var/containers/Bundle/Application/11FCF868-7563-476A-B6D2-458CF8C149BD/App.app/jvm/java-17-openjdk
2022-12-15 13:45:21.383 PojavLauncher[1147:32484] [JavaLauncher] Restored preference: RENDERER is set to libOSMesaOverride.dylib
2022-12-15 13:45:21.383 PojavLauncher[1147:32484] [JavaLauncher] Max RAM allocation is set to 500 MB
2022-12-15 13:45:21.383 PojavLauncher[1147:32484] [JavaLauncher] Java executable path: /var/containers/Bundle/Application/11FCF868-7563-476A-B6D2-458CF8C149BD/App.app/jvm/java-17-openjdk/bin/java
2022-12-15 13:45:21.522 PojavLauncher[1147:32484] [Init] Found JLI lib
2022-12-15 13:45:21.522 PojavLauncher[1147:32484] [Init] Calling JLI_Launch
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.lang.System.getenv(String)" is null
	at com.github.caciocavallosilano.cacio.ctc.CTCScreen.<clinit>(CTCScreen.java:140)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.getPlatformWindowFactory(CTCToolkit.java:67)
	at com.github.caciocavallosilano.cacio.peer.CacioToolkit.<init>(CacioToolkit.java:112)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.<init>(CTCToolkit.java:59)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:55)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:49)
Launching Minecraft fabric-loader-0.14.11-1.19.2
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
Args init finished. Now starting game
2022-12-15 13:45:24.975 PojavLauncher[1147:33795] Error
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: java.io.IOException: error reading /private/var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/instances/default/versions/fabric-loader-0.14.11-1.19.2/fabric-loader-0.14.11-1.19.2.jar
	at net.fabricmc.loader.impl.util.ExceptionUtil.wrap(ExceptionUtil.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:232)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 7 more
Caused by: java.io.IOException: error reading /private/var/mobile/Containers/Data/Application/7C0DCDE3-7E0C-4CA5-8EC3-055106D26603/Documents/instances/default/versions/fabric-loader-0.14.11-1.19.2/fabric-loader-0.14.11-1.19.2.jar
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:214)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:161)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:187)
	... 11 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at net.fabricmc.loader.impl.game.LibClassifier.process(LibClassifier.java:201)
	... 13 more

### Steps To Reproduce

```markdown
1.Open PojavLauncher 
2.Launch the game on a demo account
3.Game crash
```

### Expected Behavior

I expect the Mojang logo loading

### Platform

```markdown
- Device model: iPhone 7
- iOS version: 15.7.1
- PojavLauncher version: 2.1
```

**Comment by khanhduytran0** [comment]
Enable `check files after downloading`
