### ISSUE TITLE
[error] the game is exited with error 6

### ISSUE THREAD

**Issue by kenny000001** [PojavLauncherTeam/PojavLauncher_iOS#460]
### Describe the bug

When I opened  the Minecraft with optifine,my iPhone pops up “ exited with error 6”.
I think it is needs to update something,and I don’t use except the optifine.

### The log file and images/videos
```
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
[05:54:30] [Server thread/INFO]: Starting integrated minecraft server version 1.19.2
[05:54:30] [Server thread/INFO]: Generating keypair
[05:55:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[05:55:23] [Render thread/INFO]: 准备生成区域中：0%
[05:55:23] [Render thread/INFO]: 准备生成区域中：0%
[05:55:23] [Render thread/INFO]: 准备生成区域中：0%
[05:55:24] [Render thread/INFO]: 准备生成区域中：0%
[05:55:25] [Render thread/INFO]: 准备生成区域中：0%
[05:55:26] [Render thread/INFO]: 准备生成区域中：0%
[05:55:26] [Render thread/INFO]: 准备生成区域中：0%
[05:55:26] [Render thread/INFO]: 准备生成区域中：0%
[05:55:27] [Render thread/INFO]: 准备生成区域中：0%
[05:55:27] [Render thread/INFO]: 准备生成区域中：0%
[05:55:27] [Render thread/INFO]: 准备生成区域中：30%
[05:55:28] [Render thread/INFO]: 准备生成区域中：30%
[05:55:29] [Render thread/INFO]: 准备生成区域中：30%
[05:55:29] [Render thread/INFO]: 准备生成区域中：30%
[05:55:29] [Render thread/INFO]: 准备生成区域中：30%
[05:55:30] [Render thread/INFO]: 准备生成区域中：30%
[05:55:31] [Render thread/INFO]: 准备生成区域中：30%
[05:55:31] [Render thread/INFO]: 准备生成区域中：30%
[05:55:32] [Render thread/INFO]: 准备生成区域中：30%
[05:55:32] [Render thread/INFO]: 准备生成区域中：30%
[05:55:33] [Render thread/INFO]: 准备生成区域中：30%
[05:55:33] [Render thread/INFO]: 准备生成区域中：30%
[05:55:34] [Render thread/INFO]: 准备生成区域中：30%
[05:55:34] [Render thread/INFO]: 准备生成区域中：30%
[05:55:35] [Render thread/INFO]: 准备生成区域中：30%
[05:55:35] [Render thread/INFO]: 准备生成区域中：30%
[05:55:36] [Render thread/INFO]: 准备生成区域中：30%
[05:55:36] [Render thread/INFO]: 准备生成区域中：30%
[05:55:37] [Render thread/INFO]: 准备生成区域中：30%
[05:55:37] [Render thread/INFO]: 准备生成区域中：30%
[05:55:38] [Render thread/INFO]: 准备生成区域中：30%
[05:55:38] [Render thread/INFO]: 准备生成区域中：30%
[05:55:39] [Render thread/INFO]: 准备生成区域中：30%
[05:55:39] [Render thread/INFO]: 准备生成区域中：30%
[05:55:40] [Render thread/INFO]: 准备生成区域中：30%
[05:55:41] [Render thread/INFO]: 准备生成区域中：30%
[05:55:41] [Render thread/INFO]: 准备生成区域中：30%
[05:55:41] [Render thread/INFO]: 准备生成区域中：30%
[05:55:42] [Render thread/INFO]: 准备生成区域中：30%
[05:55:42] [Render thread/INFO]: 准备生成区域中：31%
[05:55:42] [Render thread/INFO]: 准备生成区域中：31%
[05:55:43] [Render thread/INFO]: 准备生成区域中：31%
[05:55:43] [Render thread/INFO]: 准备生成区域中：31%
[05:55:44] [Render thread/INFO]: 准备生成区域中：31%
[05:55:45] [Render thread/INFO]: 准备生成区域中：31%
[05:55:45] [Render thread/INFO]: 准备生成区域中：31%
[05:55:46] [Render thread/INFO]: 准备生成区域中：31%
[05:55:46] [Render thread/INFO]: 准备生成区域中：31%
[05:55:47] [Render thread/INFO]: 准备生成区域中：31%
[05:55:47] [Render thread/INFO]: 准备生成区域中：32%
[05:55:48] [Render thread/INFO]: 准备生成区域中：33%
[05:55:48] [Render thread/INFO]: 准备生成区域中：33%
[05:55:49] [Render thread/INFO]: 准备生成区域中：33%
[05:55:49] [Render thread/INFO]: 准备生成区域中：33%
[05:55:50] [Render thread/INFO]: 准备生成区域中：34%
[05:55:50] [Render thread/INFO]: 准备生成区域中：34%
[05:55:51] [Render thread/INFO]: 准备生成区域中：34%
[05:55:51] [Render thread/INFO]: 准备生成区域中：34%
[05:55:52] [Render thread/INFO]: 准备生成区域中：35%
[05:55:52] [Render thread/INFO]: 准备生成区域中：35%
[05:55:53] [Render thread/INFO]: 准备生成区域中：35%
[05:55:53] [Render thread/INFO]: 准备生成区域中：35%
[05:55:54] [Render thread/INFO]: 准备生成区域中：35%
[05:55:54] [Render thread/INFO]: 准备生成区域中：36%
[05:55:55] [Render thread/INFO]: 准备生成区域中：36%
[05:55:55] [Render thread/INFO]: 准备生成区域中：36%
[05:55:55] [Render thread/INFO]: 准备生成区域中：37%
[05:55:56] [Render thread/INFO]: 准备生成区域中：37%
[05:55:57] [Render thread/INFO]: 准备生成区域中：37%
[05:55:57] [Render thread/INFO]: 准备生成区域中：38%
[05:55:58] [Render thread/INFO]: 准备生成区域中：38%
[05:55:58] [Render thread/INFO]: 准备生成区域中：38%
[05:55:59] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 5112736256, width=2712, height=1250
[05:55:59] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 5112736256, width=2712, height=1250
[05:55:59] [Render thread/INFO]: 准备生成区域中：39%
[05:55:59] [Render thread/INFO]: 准备生成区域中：39%
[05:56:00] [Render thread/INFO]: 准备生成区域中：39%
[05:56:00] [Render thread/INFO]: 准备生成区域中：39%
[05:56:01] [Render thread/INFO]: 准备生成区域中：39%
[05:56:01] [Render thread/INFO]: 准备生成区域中：40%
[05:56:02] [Render thread/INFO]: 准备生成区域中：40%
[05:56:02] [Render thread/INFO]: 准备生成区域中：40%
[05:56:03] [Render thread/INFO]: 准备生成区域中：40%
[05:56:03] [Render thread/INFO]: 准备生成区域中：40%
[05:56:04] [Render thread/INFO]: 准备生成区域中：41%
[05:56:04] [Render thread/INFO]: 准备生成区域中：41%
[05:56:04] [Render thread/INFO]: 准备生成区域中：41%
[05:56:05] [Render thread/INFO]: 准备生成区域中：42%
[05:56:06] [Render thread/INFO]: 准备生成区域中：42%
[05:56:06] [Render thread/INFO]: 准备生成区域中：42%
[05:56:07] [Render thread/INFO]: 准备生成区域中：42%
[05:56:07] [Render thread/INFO]: 准备生成区域中：42%
[05:56:08] [Render thread/INFO]: 准备生成区域中：43%
[05:56:08] [Render thread/INFO]: 准备生成区域中：43%
[05:56:09] [Render thread/INFO]: 准备生成区域中：43%
[05:56:09] [Render thread/INFO]: 准备生成区域中：44%
[05:56:09] [Render thread/INFO]: 准备生成区域中：44%
[05:56:10] [Render thread/INFO]: 准备生成区域中：44%
[05:56:11] [Render thread/INFO]: 准备生成区域中：44%
[05:56:11] [Render thread/INFO]: 准备生成区域中：44%
[05:56:12] [Render thread/INFO]: 准备生成区域中：44%
[05:56:12] [Render thread/INFO]: 准备生成区域中：45%
[05:56:13] [Render thread/INFO]: 准备生成区域中：45%
[05:56:13] [Render thread/INFO]: 准备生成区域中：45%
[05:56:14] [Render thread/INFO]: 准备生成区域中：46%
[05:56:14] [Render thread/INFO]: 准备生成区域中：46%
[05:56:15] [Render thread/INFO]: 准备生成区域中：47%
[05:56:15] [Render thread/INFO]: 准备生成区域中：48%
[05:56:16] [Render thread/INFO]: 准备生成区域中：48%
[05:56:16] [Render thread/INFO]: 准备生成区域中：48%
[05:56:17] [Render thread/INFO]: 准备生成区域中：49%
[05:56:17] [Render thread/INFO]: 准备生成区域中：49%
[05:56:18] [Render thread/INFO]: 准备生成区域中：50%
[05:56:18] [Render thread/INFO]: 准备生成区域中：51%
[05:56:19] [Render thread/INFO]: 准备生成区域中：52%
[05:56:19] [Render thread/INFO]: 准备生成区域中：52%
[05:56:20] [Render thread/INFO]: 准备生成区域中：52%
[05:56:20] [Render thread/INFO]: 准备生成区域中：53%
[05:56:20] [Render thread/INFO]: 准备生成区域中：54%
[05:56:21] [Render thread/INFO]: 准备生成区域中：54%
[05:56:22] [Render thread/INFO]: 准备生成区域中：54%
[05:56:22] [Render thread/INFO]: 准备生成区域中：54%
[05:56:23] [Render thread/INFO]: 准备生成区域中：55%
[05:56:23] [Render thread/INFO]: 准备生成区域中：55%
[05:56:24] [Render thread/INFO]: 准备生成区域中：56%
[05:56:24] [Render thread/INFO]: 准备生成区域中：56%
[05:56:24] [Render thread/INFO]: 准备生成区域中：56%
[05:56:25] [Render thread/INFO]: 准备生成区域中：56%
[05:56:26] [Render thread/INFO]: 准备生成区域中：56%
[05:56:26] [Render thread/INFO]: 准备生成区域中：57%
[05:56:26] [Render thread/INFO]: 准备生成区域中：57%
[05:56:27] [Render thread/INFO]: 准备生成区域中：57%
[05:56:28] [Render thread/INFO]: 准备生成区域中：58%
[05:56:28] [Render thread/INFO]: 准备生成区域中：58%
[05:56:29] [Render thread/INFO]: 准备生成区域中：58%
[05:56:29] [Render thread/INFO]: 准备生成区域中：58%
[05:56:30] [Render thread/INFO]: 准备生成区域中：59%
[05:56:30] [Render thread/INFO]: 准备生成区域中：60%
[05:56:30] [Render thread/INFO]: 准备生成区域中：60%
[05:56:31] [Render thread/INFO]: 准备生成区域中：61%
[05:56:31] [Render thread/INFO]: 准备生成区域中：61%
[05:56:32] [Render thread/INFO]: 准备生成区域中：62%
[05:56:33] [Render thread/INFO]: 准备生成区域中：63%
[05:56:33] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 5112736256, width=1250, height=2712
[05:56:33] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 5112736256, width=1250, height=2712
[05:56:33] [Render thread/INFO]: 准备生成区域中：64%
[05:56:33] [Render thread/INFO]: 准备生成区域中：64%
[05:56:34] [Render thread/INFO]: 准备生成区域中：65%
[05:56:35] [Render thread/INFO]: 准备生成区域中：66%
[05:56:35] [Render thread/INFO]: 准备生成区域中：67%
[05:56:36] [Render thread/INFO]: 准备生成区域中：68%
[05:56:36] [Render thread/INFO]: 准备生成区域中：68%
[05:56:37] [Render thread/INFO]: 准备生成区域中：68%
[05:56:37] [Render thread/INFO]: 准备生成区域中：69%
[05:56:38] [Render thread/INFO]: 准备生成区域中：70%
[05:56:38] [Render thread/INFO]: 准备生成区域中：70%
[05:56:39] [Render thread/INFO]: 准备生成区域中：71%
[05:56:39] [Render thread/INFO]: 准备生成区域中：71%
[05:56:39] [Render thread/INFO]: 准备生成区域中：71%
[05:56:40] [Render thread/INFO]: 准备生成区域中：71%
[05:56:40] [Render thread/INFO]: 准备生成区域中：72%
[05:56:41] [Render thread/INFO]: 准备生成区域中：72%
[05:56:41] [Render thread/INFO]: 准备生成区域中：72%
[05:56:42] [Render thread/INFO]: 准备生成区域中：72%
[05:56:42] [Render thread/INFO]: 准备生成区域中：73%
[05:56:43] [Render thread/INFO]: 准备生成区域中：74%
[05:56:44] [Render thread/INFO]: 准备生成区域中：75%
[05:56:44] [Render thread/INFO]: 准备生成区域中：75%
[05:56:45] [Render thread/INFO]: 准备生成区域中：75%
[05:56:45] [Render thread/INFO]: 准备生成区域中：76%
[05:56:46] [Render thread/INFO]: 准备生成区域中：77%
[05:56:46] [Render thread/INFO]: 准备生成区域中：78%
[05:56:47] [Render thread/INFO]: 准备生成区域中：79%
[05:56:47] [Render thread/INFO]: 准备生成区域中：79%
[05:56:48] [Render thread/INFO]: 准备生成区域中：80%
[05:56:48] [Render thread/INFO]: 准备生成区域中：81%
[05:56:48] [Render thread/INFO]: 准备生成区域中：82%
[05:56:49] [Render thread/INFO]: 准备生成区域中：83%
[05:56:50] [Render thread/INFO]: 准备生成区域中：83%
[05:56:50] [Render thread/INFO]: 准备生成区域中：83%
[05:56:51] [Render thread/INFO]: 准备生成区域中：85%
[05:56:51] [Render thread/INFO]: 准备生成区域中：86%
[05:56:51] [Render thread/INFO]: 准备生成区域中：86%
[05:56:52] [Render thread/INFO]: 准备生成区域中：86%
[05:56:53] [Render thread/INFO]: 准备生成区域中：86%
[05:56:53] [Render thread/INFO]: 准备生成区域中：87%
[05:56:54] [Render thread/INFO]: 准备生成区域中：87%
[05:56:54] [Render thread/INFO]: 准备生成区域中：88%
[05:56:55] [Render thread/INFO]: 准备生成区域中：88%
[05:56:55] [Render thread/INFO]: 准备生成区域中：89%
[05:56:56] [Render thread/INFO]: 准备生成区域中：90%
[05:56:56] [Render thread/INFO]: 准备生成区域中：90%
[05:56:56] [Render thread/INFO]: 准备生成区域中：91%
[05:56:57] [Render thread/INFO]: 准备生成区域中：92%
[05:56:58] [Render thread/INFO]: 准备生成区域中：93%
[05:56:58] [Render thread/INFO]: 准备生成区域中：94%
[05:56:58] [Render thread/INFO]: 准备生成区域中：95%
[05:56:59] [Render thread/INFO]: 准备生成区域中：96%
[05:57:00] [Render thread/INFO]: 准备生成区域中：98%
[05:57:00] [Render thread/INFO]: 准备生成区域中：99%
[05:57:00] [Render thread/INFO]: Time elapsed: 97581 ms
[05:57:00] [Server thread/INFO]: Changing view distance to 9, from 10
[05:57:00] [Server thread/INFO]: Changing simulation distance to 7, from 0
[05:57:02] [Server thread/INFO]: xiekenny[local:E:cd904533] logged in with entity id 93 at (8.5, 74.0, 23.5)
[05:57:02] [Server thread/INFO]: xiekenny加入了游戏
[05:57:03] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2033ms or 40 ticks behind
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: none, at: bindDataLocation
[05:57:08] [Render thread/INFO]: [System] [CHAT] §eOpenGL错误§f：1282（Invalid operation）
[05:57:08] [Render thread/INFO]: [Shaders] Program loaded: final
[05:57:08] [Render thread/INFO]: [Shaders] usedColorBuffers: 4
[05:57:08] [Render thread/INFO]: [Shaders] usedDepthBuffers: 1
[05:57:08] [Render thread/INFO]: [Shaders] usedShadowColorBuffers: 0
[05:57:08] [Render thread/INFO]: [Shaders] usedShadowDepthBuffers: 0
[05:57:08] [Render thread/INFO]: [Shaders] usedColorAttachs: 4
[05:57:08] [Render thread/INFO]: [Shaders] usedDrawBuffers: 1
[05:57:08] [Render thread/INFO]: [Shaders] bindImageTextures: false
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorA
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorA
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorA
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorA
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorB
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorB
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorB
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: FBS dfb colorB
[05:57:08] [Render thread/ERROR]: [Shaders] [Shaders] Error creating framebuffer: dfb, status: 36054
[05:57:08] [Render thread/INFO]: [System] [CHAT] [Shaders] Error creating framebuffer: dfb, status: 36054
[05:57:08] [Render thread/ERROR]: [Shaders] OpenGL error: 1280 (Invalid enum), program: none, at: preCelestialRotate
[05:57:08] [Render thread/INFO]: [Shaders] Reset model renderers
[05:57:08] [Render thread/INFO]: [Shaders] Reset world renderers
FATAL ERROR in native method: Thread[Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL20C.glVertexAttrib2s(Native Method)
	at org.lwjgl.opengl.GL20.glVertexAttrib2s(GL20.java:1503)
	at net.optifine.shaders.Shaders.setDefaultAttribLightmap(Shaders.java:7236)
	at net.optifine.shaders.Shaders.setDefaultAttribLightmap(Shaders.java:7219)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4990)
	at ezl.a(GameRenderer.java:1505)
	at ezl.a(GameRenderer.java:1191)
	at efu.f(SourceFile:1177)
	at efu.e(SourceFile:768)
	at net.minecraft.client.main.Main.a(SourceFile:244)
	at net.minecraft.client.main.Main.main(SourceFile:51)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.5-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.5-internal/Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.5-internal/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@17.0.5-internal/Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.5-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.5-internal/Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.5-internal/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@17.0.5-internal/Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
2022-12-19 13:57:09.019 PojavLauncher[12697:1553404] abort() called
```
### Steps To Reproduce

```markdown
1.start PojavLauncher 
2.open the Minecraft with optifine 
3.open or make a new world 
4.if you go to the 100%,then pops up ”exited with error 6”.
```

### Expected Behavior

I expect log in to the world 

### Platform

```markdown
- Device model: iPhone X 
- iOS version: 15.2
- PojavLauncher version: 2.1.1
```

**Comment by kenny000001** [comment]
My English isn’t good

**Comment by kenny000001** [comment]
I see this again,it’s like is the OpenGL error

**Comment by khanhduytran0** [comment]
It seems that ANGLE does not yet support `glVertexAttrib2s` function. Might be able to wrap it to other `glVertexAttrib2` but I’ll need to look into.

**Comment by kenny000001** [comment]
Ok

**Comment by kenny000001** [comment]
Emm,did you fix the error?

**Comment by khanhduytran0** [comment]
I need the shaderpack. Also, send latestlog.txt as file.

**Comment by kenny000001** [comment]
Did me give you txt now?

**Comment by kenny000001** [comment]
Did me give you again the txt ?

**Comment by kenny000001** [comment]
Emmmm

**Comment by kenny000001** [comment]
Need I get txt again?

**Comment by kenny000001** [comment]
Need me give txt to you again?

**Comment by kenny000001** [comment]
[latestlog 2.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/10298160/latestlog.2.txt)

**Comment by kenny000001** [comment]
Emmm, I don’t use shaderpack did you know.

**Comment by kenny000001** [comment]
Okay,i don’t write that ,sorry

**Comment by khanhduytran0** [comment]
> Emmm, I don’t use shaderpack did you know.

Not until I see your log
> [06:56:15] [Render thread/INFO]: [Shaders] Loaded shaderpack: (internal)

Change shader settings to none.

**Comment by crystall1nedev** [comment]
Issue with internal shaders being enabled, can't reproduce otherwise

**Comment by jusineQ** [comment]
i've had the same problem. disable 'render regions' to fix it
