### ISSUE TITLE
Can't log in or import .jar

### ISSUE THREAD

**Issue by E4rxx** [PojavLauncherTeam/PojavLauncher_iOS#465]
### Describe the bug

When attepmting to login to microsoft account, safari reports -Safari can't open the page because the certificate is not valid-.

Tried with various installation methods and it is the same (Altstore, Trollstore, deb install)

### The log file and images/videos

java.lang.ClassNotFoundException: net.minecraft.client.Main
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.kdt.pojavlaunch.uikit.UIKit.callback_JavaGUIViewController_launchJarFile(UIKit.java:87)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:53)

### Steps To Reproduce

```markdown
Use an iPhone 7 and run it as usual
```

### Expected Behavior

Expected to run the game

### Platform

```markdown
- Device model: iPhone 7 32GB 
- iOS version: 14.5.1 Jailbroken with Checkra1n
- PojavLauncher version: 2.1.1 -- Latest
```

### Anything else?

I tried with another device with the exat jar fil and it did run (ipad mini 5)

**Comment by crystall1nedev** [comment]
Unsure if this is a server issue or not, so try the latest builds.
