### ISSUE TITLE
[Bug] Games crashes using VulkanMod on 1.19.2

### ISSUE THREAD

**Issue by DermonPelado** [PojavLauncherTeam/PojavLauncher_iOS#498]
### Describe the bug

Installing vulkanmod and fabric API with fabric launcher crashes in 1.19.2

### The log file and images/videos

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2023-01-29 17:45:47
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vulkanmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.dylib
	at org.lwjgl.system.Library.loadNative(Library.java:327)
	at org.lwjgl.system.Library.loadNative(Library.java:224)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:30)
	at net.vulkanmod.config.VideoResolution.init(VideoResolution.java:55)
	at net.vulkanmod.Initializer.onInitialize(Initializer.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Mac OS X (aarch64) version 16.2
	Java Version: 17.0.5-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 263159296 bytes (250 MiB) / 718274560 bytes (685 MiB) up to 956301312 bytes (912 MiB)
	CPUs: 6
	Processor Vendor: 
	Processor Name: 
	Identifier:  Family  Model  Stepping 
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 3647.28
	Virtual memory used (MB): 2763.36
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -Xms128M -Xmx912M -Xbootclasspath/a:/var/containers/Bundle/Application/BBA1BBAE-9EE8-4C1D-BFDC-5D7A0110FDCF/App.app/libs_caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/var/containers/Bundle/Application/BBA1BBAE-9EE8-4C1D-BFDC-5D7A0110FDCF/App.app/libs_caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar -XX:-UseCompressedClassPointers
	Fabric Mods: 
		fabric-api: Fabric API 0.73.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.34+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.4+693ffc0590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.0+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.13
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		vulkanmod: VulkanMod 0.2.1
			org_joml_joml: joml 1.10.4
			org_lwjgl_lwjgl: lwjgl 3.3.1
			org_lwjgl_lwjgl-glfw: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-linux: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-glfw_natives-windows: lwjgl-glfw 3.3.1
			org_lwjgl_lwjgl-openal: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-linux: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-openal_natives-windows: lwjgl-openal 3.3.1
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.1
			org_lwjgl_lwjgl-stb: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-linux: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-stb_natives-windows: lwjgl-stb 3.3.1
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.1
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.1
			org_lwjgl_lwjgl_natives-linux: lwjgl 3.3.1
			org_lwjgl_lwjgl_natives-windows: lwjgl 3.3.1
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 

Log:
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] PojavLauncher version: 2.1.3-release, branch: 2.1.3-legacy, commit: cc887c3
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] iPhone14,5 with iOS 16.2 (Unjailbroken)
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-init] Entitlements availability:
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] - com.apple.developer.kernel.extended-virtual-addressing: NO
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] - com.apple.developer.kernel.increased-memory-limit: NO
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] - com.apple.private.security.no-sandbox: NO
2023-01-29 17:56:40.870 PojavLauncher[10927:380321] [Pre-Init] - dynamic-codesigning: NO
2023-01-29 17:56:40.956 PojavLauncher[10927:380321] [Pre-init] Restored preference: MULTI_DIR is set to default
2023-01-29 17:56:41.011 PojavLauncher[10927:380321] JitStreamer server is 69.69.0.1, attempting to connect...
2023-01-29 17:56:41.034 PojavLauncher[10927:380321] LauncherPreferences: Unknown key ram_unjb_warn
2023-01-29 17:56:41.034 PojavLauncher[10927:380321] [Pre-init] LauncherPreferences: ram_unjb_warn is NULL
2023-01-29 17:56:41.751 PojavLauncher[10927:380321] Found JitStreamer 0.2.0
2023-01-29 17:56:43.212 PojavLauncher[10927:380321] Path is file:///var/mobile/Containers/Data/Application/E7DA22C3-2F70-48CB-83F4-FEB38A8D10E7/Documents/latestlog.old.txt
2023-01-29 18:00:17.445 PojavLauncher[10927:380321] Error?: (null)
2023-01-29 18:00:17.446 PojavLauncher[10927:380321] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
*** First throw call stack:
(0x18b215e48 0x1844e78d8 0x185639398 0x100799d1c 0x100763b30 0x10076bc00 0x1928274b4 0x192828fdc 0x192837850 0x192837444 0x18b2a66d8 0x18b28803c 0x18b28cec0 0x1c52e3368 0x18d78286c 0x18d7824d0 0x10077af04 0x1a9aae960)
libc++abi: terminating with uncaught exception of type NSException

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch fabric launcher 1.19.2
```

### Expected Behavior

I expected to work

### Platform

```markdown
- Device model: iPhone 13
- iOS version: 16.2
- PojavLauncher version: 2.1.3
```

**Comment by DermonPelado** [comment]
The thing is, how I step by step install the vulkan renderer in PojavLauncher iOS? Thanks!
