### ISSUE TITLE
[Bug] World wont load after closing pojav

### ISSUE THREAD

**Issue by jack11e** [PojavLauncherTeam/PojavLauncher_iOS#535]
### Describe the bug

i made a world and then save and quit the world and press quit game in main menu now when i rejoin, it just doesn't load

### The log file and images/videos

2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] PojavLauncher version: 2.1.3-release, branch: 2.1.3-legacy, commit: cc887c3
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] iPhone12,8 with iOS 16.4 (Unjailbroken)
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-init] Entitlements availability:
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] - com.apple.developer.kernel.extended-virtual-addressing: NO
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] - com.apple.developer.kernel.increased-memory-limit: NO
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] - com.apple.private.security.no-sandbox: NO
2023-04-05 08:33:01.648 PojavLauncher[3736:565505] [Pre-Init] - dynamic-codesigning: NO
2023-04-05 08:33:01.795 PojavLauncher[3736:565505] [Pre-init] Restored preference: MULTI_DIR is set to default
2023-04-05 08:33:01.968 PojavLauncher[3736:565505] JitStreamer server is 69.69.0.1, attempting to connect...
Inspection is enabled by default for process or parent application with 'get-task-allow' entitlement linked against old SDK. Use `inspectable` API to enable inspection on newer SDKs.
2023-04-05 08:33:02.022 PojavLauncher[3736:565505] LauncherPreferences: Unknown key ram_unjb_warn
2023-04-05 08:33:02.022 PojavLauncher[3736:565505] [Pre-init] LauncherPreferences: ram_unjb_warn is NULL
2023-04-05 08:33:03.230 PojavLauncher[3736:565505] Found JitStreamer 0.2.0
2023-04-05 08:33:07.468 PojavLauncher[3736:565505] Error?: (null)
2023-04-05 08:33:11.807 PojavLauncher[3736:565505] [MCDL] Begin: download libraries
2023-04-05 08:33:11.944 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1
2023-04-05 08:33:11.945 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-linux
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows-x86
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-linux
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows-x86
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-linux
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows-x86
2023-04-05 08:33:11.946 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-linux
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows-x86
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-linux
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows-x86
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-linux
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-x86
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-linux
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos-arm64
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows
2023-04-05 08:33:11.947 PojavLauncher[3736:565505] [MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows-x86
2023-04-05 08:33:11.989 PojavLauncher[3736:565505] [MCDL] Finished: download libraries
2023-04-05 08:33:11.989 PojavLauncher[3736:565505] [MCDL] Begin: download assets
2023-04-05 08:33:19.948 PojavLauncher[3736:565505] [MCDL] Finished: download assets
2023-04-05 08:33:20.545 PojavLauncher[3736:565526] [MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/versions/1.19.3/1.19.3.json, have to assume it's good.
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] Beginning JVM launch
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] Attempting to change to Java 17 (actual might be higher)
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] JAVA_HOME is now set to /var/containers/Bundle/Application/40F79023-642B-433F-8B84-9765FDF654F2/App.app/jvm/java-17-openjdk
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] Restored preference: RENDERER is set to auto
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] Max RAM allocation is set to 740 MB
2023-04-05 08:33:20.553 PojavLauncher[3736:565526] [JavaLauncher] Java executable path: /var/containers/Bundle/Application/40F79023-642B-433F-8B84-9765FDF654F2/App.app/jvm/java-17-openjdk/bin/java
2023-04-05 08:33:20.592 PojavLauncher[3736:565526] [Init] Found JLI lib
2023-04-05 08:33:20.592 PojavLauncher[3736:565526] [Init] Calling JLI_Launch
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.lang.System.getenv(String)" is null
	at com.github.caciocavallosilano.cacio.ctc.CTCScreen.<clinit>(CTCScreen.java:140)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.getPlatformWindowFactory(CTCToolkit.java:67)
	at com.github.caciocavallosilano.cacio.peer.CacioToolkit.<init>(CacioToolkit.java:112)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.<init>(CTCToolkit.java:59)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:55)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:49)
Launching Minecraft 1.19.3
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
Args init finished. Now starting game
2023-04-05 08:33:22,318 main ERROR appender Console has no parameter that matches element Policies
[08:33:22] [main/WARN]: Failed sysctl call: hw.packages, Error code: 1
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
[08:33:22] [main/WARN]: Failed sysctl call: vm.swapusage, Error code: 1
[08:33:24] [main/INFO]: Building optimized datafixer
[08:33:27] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:33:28] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.16.29.jar:?]
	at ejf.a(SourceFile:724) ~[1.19.3.jar:?]
	at ejf.<init>(SourceFile:437) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.16.29.jar:?]
	... 13 more
[08:33:28] [Render thread/INFO]: Setting user: nigga
[08:33:28] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
LIBGL: Initialising gl4es
LIBGL: v1.1.4 built on Sep 16 2022 03:53:40
LIBGL: Using GLES 2.0 backend
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 31
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Hardware vendor is Google Inc.
LIBGL: Max Color Attachments: 4 / Draw buffers: 4
LIBGL: sRGB surface supported
LIBGL: Targeting OpenGL 2.1
LIBGL: No hack in shader converter to define overloaded function with int
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: glX Will try to recycle EGL Surface
LIBGL: Current folder is:/private/var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/instances/default
2023-04-05 08:33:28.624 PojavLauncher[3736:565685] Debug log not enabled.
[08:33:30] [Render thread/ERROR]: Couldn't set icon
java.nio.file.NoSuchFileException: /var/mobile/Containers/Data/Application/3C0521A0-BD43-459C-9E2B-8F3F3A8B3403/Documents/Library/Application Support/minecraft/assets/objects/99/991b421dfd401f115241601b2b373140a8d78572
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at aja.newByteChannel(SourceFile:68) ~[1.19.3.jar:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:?]
	at java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
	at ajw.a(SourceFile:13) ~[1.19.3.jar:?]
	at eda.a(SourceFile:40) ~[1.19.3.jar:?]
	at ejf.<init>(SourceFile:495) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102) ~[launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar:?]
[08:33:30] [Render thread/WARN]: Failed sysctl call: hw.packages, Error code: 1
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.brand_string, Error code: 1
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.vendor, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.stepping, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.model, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.family, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.signature, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: machdep.cpu.feature_bits, Error code: 2
[08:33:30] [Render thread/WARN]: Failed sysctl call: hw.cpufrequency, Error code: 2
[08:33:31] [Worker-Main-7/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at eyv.a(SourceFile:139) ~[1.19.3.jar:?]
	at eyv.b(SourceFile:79) ~[1.19.3.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[08:33:31] [Render thread/INFO]: Reloading ResourceManager: vanilla
[08:33:31] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[08:33:34] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[08:33:34] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[08:33:35] [Render thread/INFO]: OpenAL initialized on device CoreAudio Default
[08:33:35] [Render thread/INFO]: Sound engine started
[08:33:35] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[08:33:35] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[08:33:35] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08:33:35] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08:33:35] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08:33:35] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08:33:35] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08:33:35] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[08:33:36] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[08:33:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[08:33:36] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[08:33:39] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 4314231296, width=1334, height=750
[08:33:39] [Render thread/INFO]: [STDOUT]: GLFW: Set size for window 4314231296, width=1334, height=750
[08:33:51] [Render thread/INFO]: Loaded 7 recipes
[08:33:52] [Render thread/INFO]: Loaded 1179 advancements
[08:33:53] [Server thread/INFO]: Starting integrated minecraft server version 1.19.3
[08:33:53] [Server thread/INFO]: Generating keypair
[08:33:59] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld

### Steps To Reproduce

```markdown
1. Make world
2. Sace and quit 
3. Quit pojav (main menu)
4. Reopen pojav
5. Go to singleplayer
6. Join my world
7. Wont load
```

### Expected Behavior

I expected to re enter my world like normal

### Platform

```markdown
- Device model: iPhone SE 2nd gen
- iOS version: 16.4
- PojavLauncher version: 2.1.3
```

**Comment by crystall1nedev** [comment]
Seems to be an issue in 2.1.3 and older, however not present in 2.2 development builds. Closing.
