### ISSUE TITLE
When using fabric I get a black screen with the gui that has the touch controls

### ISSUE THREAD

**Issue by PerennialWheatSA** [PojavLauncherTeam/PojavLauncher_iOS#55]
The title says it all and here is my log file

`2021-02-18 11:12:27.526 PojavLauncher[47050:558971] Found JLI lib
2021-02-18 11:12:27.526 PojavLauncher[47050:558971] Calling JLI_Launch
[0.072s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016da50000-0x000000016da5c000).
[0.072s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-18 11:12:28.861 PojavLauncher[47050:558960] libpojavexec loaded from vm=0x101121e50
Task validate successful
Finding a version
Selected Minecraft version: fabric-loader-0.11.1-1.16.5
Downloading version list
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Downloading fabric-loader-0.11.1-1.16.5.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading fabric-loader-0.11.1-1.16.5.jar
Download error, skipping
java.io.IOException: Permission denied
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createTempFile(File.java:2106)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:56)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:698)
	at net.kdt.pojavlaunch.PLaunchApp.lambda$installMinecraft$0(PLaunchApp.java:165)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-02-18 11:12:41.919 PojavLauncher[47050:558960] MGLKViewController viewDidLoad
2021-02-18 11:12:41.923 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:41.923 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:41.923 PojavLauncher[47050:558960] MGLKViewController resume
2021-02-18 11:12:41.933 PojavLauncher[47050:558960] Received SurfaceViewController callback, width=2048, height=1536
Saving GLES context
Launching Minecraft fabric-loader-0.11.1-1.16.5
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
2021-02-18 11:12:42.180 PojavLauncher[47050:558960] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x13885f570>)
Args init finished. Now starting game
2021-02-18 11:12:42.243 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:42.742 PojavLauncher[47050:558960] MGLKViewController viewDidAppear
2021-02-18 11:12:42.742 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:42.742 PojavLauncher[47050:558960] MGLKViewController resume
2021-02-18 11:12:42.749 PojavLauncher[47050:558960] MGLKViewController pause
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
19:12:43.485 [Thread-1] ERROR FabricLoader - Could not find valid game provider!
19:12:43.489 [Thread-1] ERROR FabricLoader - - Minecraft
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:118)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Could not find valid game provider!
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:96)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	... 6 more

2021-02-18 11:12:44.530 PojavLauncher[47050:558960] MGLKViewController appWillPause:
2021-02-18 11:12:44.530 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:45.383 PojavLauncher[47050:558960] MGLKViewController pause
2021-02-18 11:12:45.563 PojavLauncher[47050:558960] MGLKViewController pause

**Also here is the log file in the log folder** 

[04:53:38] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:53:39] [Render thread/INFO]: Setting user: PerennialWheat
[04:53:39] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[04:53:46] [Render thread/INFO]: Reloading ResourceManager: Default
[04:53:46] [Worker-Main-4/WARN]: File minecraft:sounds/ambient/nether/warped_forest/mood2.ogg does not exist, cannot add it to event minecraft:ambient.warped_forest.mood
[04:53:46] [Worker-Main-4/WARN]: File minecraft:sounds/ambient/nether/warped_forest/mood5.ogg does not exist, cannot add it to event minecraft:ambient.warped_forest.mood
[04:53:46] [Worker-Main-4/WARN]: File minecraft:sounds/ambient/nether/soulsand_valley/sand1.ogg does not exist, cannot add it to event minecraft:ambient.soul_sand_valley.additions
[04:53:46] [Worker-Main-4/WARN]: File minecraft:sounds/ambient/nether/nether_wastes/ambience.ogg does not exist, cannot add it to event minecraft:ambient.nether_wastes.loop
[04:53:47] [Worker-Main-4/WARN]: File minecraft:sounds/music/game/nether/soulsand_valley/so_below.ogg does not exist, cannot add it to event minecraft:music.nether.basalt_deltas
[04:53:47] [Worker-Main-4/WARN]: File minecraft:sounds/music/game/nether/nether_wastes/rubedo.ogg does not exist, cannot add it to event minecraft:music.nether.nether_wastes
[04:53:47] [Worker-Main-4/WARN]: File minecraft:sounds/music/game/nether/soulsand_valley/so_below.ogg does not exist, cannot add it to event minecraft:music.nether.soul_sand_valley
[04:53:47] [Worker-Main-4/WARN]: File minecraft:sounds/music/game/water/shuniji.ogg does not exist, cannot add it to event minecraft:music.under_water
[04:53:47] [Worker-Main-4/WARN]: File minecraft:sounds/music/game/water/dragon_fish.ogg does not exist, cannot add it to event minecraft:music.under_water
[04:54:16] [Render thread/INFO]: OpenAL initialized.
[04:54:16] [Render thread/INFO]: Sound engine started
[04:54:17] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[04:54:17] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[04:54:17] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[04:54:17] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[04:54:17] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[04:54:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[04:54:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[04:54:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[04:54:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[04:54:21] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[04:54:27] [Render thread/INFO]: Stopping!
[04:54:28] [Render thread/ERROR]: Deleting stream buffers: Invalid name parameter.

**Comment by khanhduytran0** [comment]
Get the latest build.

**Comment by PerennialWheat** [comment]
> Get the latest build.

Same error with the latest release build

**Comment by khanhduytran0** [comment]
@PerennialWheat
Latest action build (nightly build) ≠ latest release

**Comment by Doregon** [comment]
Closing stale issue.
