### ISSUE TITLE
Forge 1.7.10 crash due to NoClassDefFoundError exception for java/util/jar/Pack200

### ISSUE THREAD

**Issue by BruhMoment69420-debug** [PojavLauncherTeam/PojavLauncher_iOS#57]
Pack200 seems to be a part of the standard library that was removed with Java 14. The game crashes when it is started, maybe a stub reimplementation of Pack200 could fix it because its just something to do with jar compression, but I don’t know Java

Version 39b21f6380a62891bdc4de4226c6c75f20d30d94 (latest build at the time of this post)

`[12:45:11] [Thread-1/INFO] [STDERR]: [net.kdt.pojavlaunch.Tools:showError:444]: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NoClassDefFoundError: java/util/jar/Pack200
	at cpw.mods.fml.common.patcher.ClassPatchManager.setup(ClassPatchManager.java:161)
	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:181)
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
Caused by: java.lang.ClassNotFoundException: java.util.jar.Pack200
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) `

[Full log](https://pastebin.com/pX1ZzgTN)

**Comment by khanhduytran0** [comment]
I tried to put java.util.jar.pack200 related stuff to boot class path, it stills `NoClassDefFoundError `

**Comment by khanhduytran0** [comment]
Java 8 is out and Forge 1.7.10 should work now.
