### ISSUE TITLE
Crash when using forge 1.20.1

### ISSUE THREAD

**Issue by RedstoneGithub** [PojavLauncherTeam/PojavLauncher_iOS#623]
### Describe the bug

1.19 forge works fine, 1.20.1 crashes immediately. iPhone 14 pro with iOS 17.1.1. Log:

```

Pre-Init] PojavLauncher INIT!
[Pre-Init] Version: 2.2-development
[Pre-Init] Commit: d9877bc (main)
[Pre-Init] Device: iPhone 14 Pro
[Pre-Init] iOS 17.1.1 (Unjailbroken)
[Pre-init] Entitlements availability:
* com.apple.developer.kernel.extended-virtual-addressing: NO
* com.apple.developer.kernel.increased-memory-limit: NO
* com.apple.private.security.no-sandbox: NO
* dynamic-codesigning: NO
[Debugging] Debug log enabled: YES
[Pre-init] Restored game directory preference (default)
[JitStreamer] Server is 69.69.0.1, attempting to connect...
[JitStreamer] Server not found or VPN not connected.
Discovering servers...
Connecting to service: <NSNetService 0x282246720> local. _altserver._tcp. MacBook Pro 60320
[MCDL] Downloading 1.20.1-forge-47.2.6
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft/versions/1.20.1-forge-47.2.6/1.20.1-forge-47.2.6.json, have to assume it's good.
[MCDL] Downloading 1.20.1
[MCDL] SHA1 passed for 1.20.1.json
[MCDL] Downloading 5
[MCDL] SHA1 passed for 5.json
[MCDL] insertSafety: how to insert assetIndex?
[MCDL] insertSafety: how to insert assets?
[MCDL] Downloading 5
[MCDL] SHA1 passed for 5.json
[MCDL] SHA1 passed for java-objc-bridge-1.1.jar
[MCDL] Begin: download libraries
[MCDL] SHA1 passed for oshi-core-6.2.2.jar
[MCDL] SHA1 passed for gson-2.10.jar
[MCDL] SHA1 passed for failureaccess-1.0.1.jar
[MCDL] SHA1 passed for guava-31.1-jre.jar
[MCDL] SHA1 passed for icu4j-71.1.jar
[MCDL] SHA1 passed for authlib-4.0.43.jar
[MCDL] SHA1 passed for blocklist-1.0.10.jar
[MCDL] SHA1 passed for brigadier-1.1.8.jar
[MCDL] SHA1 passed for datafixerupper-6.0.8.jar
[MCDL] SHA1 passed for logging-1.1.1.jar
[MCDL] SHA1 passed for patchy-2.2.10.jar
[MCDL] SHA1 passed for text2speech-1.17.9.jar
[MCDL] SHA1 passed for commons-codec-1.15.jar
[MCDL] SHA1 passed for commons-io-2.11.0.jar
[MCDL] SHA1 passed for commons-logging-1.2.jar
[MCDL] SHA1 passed for netty-buffer-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-codec-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-common-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-handler-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-resolver-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-transport-classes-epoll-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
[MCDL] SHA1 passed for netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
[MCDL] SHA1 passed for netty-transport-native-unix-common-4.1.82.Final.jar
[MCDL] SHA1 passed for netty-transport-4.1.82.Final.jar
[MCDL] SHA1 passed for fastutil-8.5.9.jar
[MCDL] SHA1 passed for jna-platform-5.12.1.jar
[MCDL] SHA1 passed for jna-5.13.0.jar
[MCDL] SHA1 passed for jopt-simple-5.0.4.jar
[MCDL] SHA1 passed for commons-compress-1.21.jar
[MCDL] SHA1 passed for commons-lang3-3.12.0.jar
[MCDL] SHA1 passed for httpclient-4.5.13.jar
[MCDL] SHA1 passed for httpcore-4.4.15.jar
[MCDL] SHA1 passed for log4j-api-2.19.0.jar
[MCDL] SHA1 passed for log4j-core-2.19.0.jar
[MCDL] SHA1 passed for log4j-slf4j2-impl-2.19.0.jar
[MCDL] SHA1 passed for joml-1.10.5.jar
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-openal:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-stb:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.3.1:natives-windows-x86
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-linux
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-macos-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows-arm64
[MCDL] Skipped library org.lwjgl:lwjgl:3.3.1:natives-windows-x86
[MCDL] SHA1 passed for slf4j-api-2.0.1.jar
[MCDL] SHA1 passed for securejarhandler-2.1.10.jar
[MCDL] SHA1 passed for asm-9.5.jar
[MCDL] SHA1 passed for asm-commons-9.5.jar
[MCDL] SHA1 passed for asm-tree-9.5.jar
[MCDL] SHA1 passed for asm-util-9.5.jar
[MCDL] SHA1 passed for asm-analysis-9.5.jar
[MCDL] SHA1 passed for accesstransformers-8.0.4.jar
[MCDL] SHA1 passed for antlr4-runtime-4.9.1.jar
[MCDL] SHA1 passed for eventbus-6.0.5.jar
[MCDL] SHA1 passed for forgespi-7.0.1.jar
[MCDL] SHA1 passed for coremods-5.0.1.jar
[MCDL] SHA1 passed for modlauncher-10.0.9.jar
[MCDL] SHA1 passed for unsafe-0.2.0.jar
[MCDL] SHA1 passed for mergetool-1.1.5-api.jar
[MCDL] SHA1 passed for core-3.6.4.jar
[MCDL] SHA1 passed for toml-3.6.4.jar
[MCDL] SHA1 passed for maven-artifact-3.8.5.jar
[MCDL] SHA1 passed for typetools-0.6.3.jar
[MCDL] SHA1 passed for terminalconsoleappender-1.2.0.jar
[MCDL] SHA1 passed for jline-reader-3.12.1.jar
[MCDL] SHA1 passed for jline-terminal-3.12.1.jar
[MCDL] SHA1 passed for mixin-0.8.5.jar
[MCDL] SHA1 passed for nashorn-core-15.3.jar
[MCDL] SHA1 passed for JarJarSelector-0.3.19.jar
[MCDL] SHA1 passed for JarJarMetadata-0.3.19.jar
[MCDL] SHA1 passed for bootstraplauncher-1.1.2.jar
[MCDL] SHA1 passed for JarJarFileSystems-0.3.19.jar
[MCDL] SHA1 passed for fmlloader-1.20.1-47.2.6.jar
[MCDL] SHA1 passed for fmlearlydisplay-1.20.1-47.2.6.jar
[MCDL] SHA1 passed for 1.20.1-forge-47.2.6.jar
[MCDL] Finished: download libraries
[MCDL] Begin: download assets
[MCDL] SHA1 passed for 3582/3583 asset files
[MCDL] Finished: download assets
Note: some files of 1.19+ are skipped to workaround an issue
Stopped discovering servers.
[MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft/versions/1.20.1-forge-47.2.6/1.20.1-forge-47.2.6.json, have to assume it's good.
[MCDL] insertSafety: how to insert assetIndex?
[MCDL] insertSafety: how to insert assets?
[JavaLauncher] Beginning JVM launch
[JavaLauncher] Attempting to change to Java 17 (actual might be higher)
[JavaLauncher] JAVA_HOME is now set to /var/containers/Bundle/Application/9B792EC4-D788-40D6-B723-DBD81FA55AED/App.app/java_runtimes/java-17-openjdk
[JavaLauncher] Restored preference: RENDERER is set to auto
[JavaLauncher] Max RAM allocation is set to 1413 MB
[Init] Found JLI lib
[Init] Calling JLI_Launch
[AltKit] Successfully enabled JIT compilation!
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Launching Minecraft 1.20.1-forge-47.2.6
Library net.java.dev.jna:jna:5.12.1 has been changed to version 5.13.0
Ignored non-exists file: /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5.jar
Ignored non-exists file: /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final.jar
Args init finished. Now starting game
2023-11-14 00:11:54,307 main ERROR appender Console has no parameter that matches element Policies
[00:11:54] [main/INFO]: ModLauncher running: args [--username, my_username_here, --version, 1.20.1, --gameDir, /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft, --assetsDir, /var/mobile/Containers/Data/Application/FED5155A-22F7-4B45-A7D4-0E7965F9412F/Documents/Library/Application Support/minecraft/assets, --assetIndex, 5, --uuid, 46f4bd896f244f4b86ab095443473339, --accessToken, ââââââââ, --clientId, 0, --xuid, 13239828519540029816, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.6, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[00:11:54] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8-internal by N/A; OS Mac OS X arch aarch64 version 17.1.1
[00:11:54] [main/FATAL]: Encountered serious error loading launch plugin service. Things will not work well
java.util.ServiceConfigurationError: cpw.mods.modlauncher.serviceapi.ILaunchPluginService: Provider net.minecraftforge.fml.loading.RuntimeDistCleaner could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderImpl.get(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.util.ServiceLoaderUtils.lambda$streamWithErrorHandling$0(ServiceLoaderUtils.java:39) ~[modlauncher-10.0.9.jar%2387!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.<init>(LaunchPluginHandler.java:46) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:65) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar%2365!/:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/api/distmarker/OnlyIn
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.<clinit>(RuntimeDistCleaner.java:42) ~[fmlloader-1.20.1-47.2.6.jar%2374!/:1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	... 24 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.api.distmarker.OnlyIn
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.<clinit>(RuntimeDistCleaner.java:42) ~[fmlloader-1.20.1-47.2.6.jar%2374!/:1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	... 24 more
[00:11:54] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[00:11:54] [main/INFO]: Trying GL version 4.6
libtinygl4angle.dylib=0xb68cebd0, error=(null)
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=37195
EGLBridge: EGLDisplay=0x105769900, EGLSurface=0x105762170
EGLBridge: Created CTX pointer = 0x10615ac00 (source = 0x0)
[00:11:54] [main/INFO]: Requested GL version 4.6 got version 0.0
GLFW: Set size for window 4397050880, width=778, height=1686
GLFW: Set size for window 4397050880, width=778, height=1686
EGLBridge: Comparing: thr=78355, this=0x10615ac00, curr=0x0
EGLBridge: Making current on window 0x10615ac00 on thread 78355
EGLBridge: eglMakeCurrent() succeed!
[00:11:54] [main/ERROR]: Dist Cleaner is missing, we need this to run
[00:11:54] [main/ERROR]: Service failed to load fml
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: Missing DistCleaner, cannot run!
	at net.minecraftforge.fml.loading.FMLLoader.lambda$onInitialLoad$2(FMLLoader.java:94) ~[fmlloader-1.20.1-47.2.6.jar%2374!/:1.0]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.FMLLoader.onInitialLoad(FMLLoader.java:92) ~[fmlloader-1.20.1-47.2.6.jar%2374!/:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.onLoad(FMLServiceProvider.java:100) ~[fmlloader-1.20.1-47.2.6.jar%2374!/:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:116) ~[modlauncher-10.0.9.jar%2387!/:?]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:116) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:48) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar%2365!/:?]
[00:11:54] [main/ERROR]: Found 1 services that failed to load : [fml]

Exception: java.lang.UnsatisfiedLinkError thrown from the UncaughtExceptionHandler in thread "main"
exit(1) called

``` 

### The log file and images/videos

In the description. 

### Steps To Reproduce

```markdown
Install forge-1.20.1-47.2.6
Start Pojavlauncher
Immediate crash before any loading screens.
```

### Expected Behavior

I expect to get to a loading screen

### Platform

```markdown
- Device model: iPhone 14 Pro
- iOS version: 17.1.1
- PojavLauncher version: 2.2
```

**Comment by GaucovyAero** [comment]
ios 17 is not supported yet
