### ISSUE TITLE
Can’t login using Mojang or Microsoft

### ISSUE THREAD

**Issue by djzdaman1** [PojavLauncherTeam/PojavLauncher_iOS#63]
Hi I have tried both login methods and neither work.
Mojang login crashes back to the Home Screen.
Microsoft login just does nothing, I press login then continue on the Microsoft screen but it doesn’t do anything.

**Comment by khanhduytran0** [comment]
Update to latest build

**Comment by djzdaman1** [comment]
Can I do that on device? I don't have access to a computer

**Comment by khanhduytran0** [comment]
Yes. Sideload the deb as how you did with v1.0.

**Comment by djzdaman1** [comment]
Where do I find it? I think I'm still on the first release lol

**Comment by khanhduytran0** [comment]
Here it is https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/591560698

**Comment by djzdaman1** [comment]
Have updated. Microsoft login still does nothing and Mojang login shows this when I click on it.

**Comment by djzdaman1** [comment]
java.lang.RuntimeException: MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:38)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:39)

**Comment by khanhduytran0** [comment]
So you haven't bought Minecraft.

**Comment by djzdaman1** [comment]
I definitely have. I’ve owned it since 2015

**Comment by khanhduytran0** [comment]
I mean you haven't bought/migrated **using** Microsoft account.

**Comment by djzdaman1** [comment]
Ah I was using the wrong email lol. I got Mojang login to work also.
