### ISSUE TITLE
[Bug] <1.16.5>

### ISSUE THREAD

**Issue by MogwartUser** [PojavLauncherTeam/PojavLauncher_iOS#633]
### Describe the bug

I wanted to install the Expensive 2.0 cheat client on 1.16.5 for 2b2t, but why does it crash a couple of seconds after launch, just like on 1.12.2. I tried to download ThunderHack 1.4 on version 1.20.2 and the same thing happened. (Expensive 2.0>versions)

### The log file and images/videos

2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] PojavLauncher version: 2.1-release, branch: main, commit: ec106e2
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] iPad11,6 with iOS 14.7.1 (TrollStore)
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-init] Entitlements availability:
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] - com.apple.developer.kernel.extended-virtual-addressing: YES
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] - com.apple.developer.kernel.increased-memory-limit: YES
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] - com.apple.private.security.no-sandbox: YES
2023-12-13 21:23:50.531 PojavLauncher[4311:324098] [Pre-Init] - dynamic-codesigning: NO
2023-12-13 21:23:50.535 PojavLauncher[4311:324098] [Pre-init] Restored preference: MULTI_DIR is set to default
2023-12-13 21:23:50.535 PojavLauncher[4311:324098] [Pre-init] Sandbox is disabled, trying to enable JIT
2023-12-13 21:23:50.549 PojavLauncher[4312:324114] parent pid is not launchd, calling ptrace(PT_TRACE_ME)
2023-12-13 21:23:50.549 PojavLauncher[4311:324098] [Pre-init] JIT has heen enabled with PT_TRACE_ME
2023-12-13 21:23:50.573 PojavLauncher[4311:324098] LauncherPreferences: Unknown key ram_unjb_warn
2023-12-13 21:23:50.573 PojavLauncher[4311:324098] [Pre-init] LauncherPreferences: ram_unjb_warn is NULL
2023-12-13 21:23:53.159 PojavLauncher[4311:324098] [MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/B11B8F66-4442-4EEE-ABCD-FAA9B8AC9D86/Documents/Library/Application Support/minecraft/versions/Expensive-2.0/Expensive-2.0.json, have to assume it's good.
2023-12-13 21:23:53.190 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: eb8bb7b66fa0e2152b1b40b3856e82f7619439ee, got: 6ef160c3133a78de015830860197602ca1c855d3)
2023-12-13 21:23:53.191 PojavLauncher[4311:324098] [MCDL] Begin: download libraries
2023-12-13 21:23:53.192 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:patchy:1.3.9
2023-12-13 21:23:53.925 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 9ddf7b048a8d701be231c0f4f95fd986198fd2d8, got: eb8bb7b66fa0e2152b1b40b3856e82f7619439ee)
2023-12-13 21:23:53.926 PojavLauncher[4311:324098] [MCDL] Downloading library oshi-project:oshi-core:1.1
2023-12-13 21:23:54.057 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: cb208278274bf12ebdb56c61bd7407e6f774d65a, got: 9ddf7b048a8d701be231c0f4f95fd986198fd2d8)
2023-12-13 21:23:54.058 PojavLauncher[4311:324098] [MCDL] Downloading library net.java.dev.jna:jna:4.4.0
2023-12-13 21:23:55.545 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: e3f70017be8100d3d6923f50b3d2ee17714e9c13, got: cb208278274bf12ebdb56c61bd7407e6f774d65a)
2023-12-13 21:23:55.546 PojavLauncher[4311:324098] [MCDL] Downloading library net.java.dev.jna:platform:3.4.0
2023-12-13 21:23:56.861 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 72c7519b6d91f7a1f993bd44a99fe95d67211b27, got: e3f70017be8100d3d6923f50b3d2ee17714e9c13)
2023-12-13 21:23:56.861 PojavLauncher[4311:324098] [MCDL] Downloading library com.ibm.icu:icu4j:66.1
2023-12-13 21:24:30.201 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 6aa6453aa99a52a5cd91749da1af6ab70e082ab3, got: 72c7519b6d91f7a1f993bd44a99fe95d67211b27)
2023-12-13 21:24:30.202 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:javabridge:1.0.22
2023-12-13 21:24:30.330 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: cdd846cfc4e0f7eefafc02c0f5dce32b9303aa2a, got: 6aa6453aa99a52a5cd91749da1af6ab70e082ab3)
2023-12-13 21:24:30.330 PojavLauncher[4311:324098] [MCDL] Downloading library net.sf.jopt-simple:jopt-simple:5.0.3
2023-12-13 21:24:30.500 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: d0626cd3108294d1d58c05859add27b4ef21f83b, got: cdd846cfc4e0f7eefafc02c0f5dce32b9303aa2a)
2023-12-13 21:24:30.500 PojavLauncher[4311:324098] [MCDL] Downloading library io.netty:netty-all:4.1.25.Final
2023-12-13 21:24:35.639 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 3a3d111be1be1b745edfa7d91678a12d7ed38709, got: d0626cd3108294d1d58c05859add27b4ef21f83b)
2023-12-13 21:24:35.639 PojavLauncher[4311:324098] [MCDL] Downloading library com.google.guava:guava:21.0
2023-12-13 21:24:39.237 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 6c6c702c89bfff3cd9e80b04d668c5e190d588c6, got: 3a3d111be1be1b745edfa7d91678a12d7ed38709)
2023-12-13 21:24:39.237 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.commons:commons-lang3:3.5
2023-12-13 21:24:39.924 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 2852e6e05fbb95076fc091f6d1780f1f8fe35e0f, got: 6c6c702c89bfff3cd9e80b04d668c5e190d588c6)
2023-12-13 21:24:39.924 PojavLauncher[4311:324098] [MCDL] Downloading library commons-io:commons-io:2.5
2023-12-13 21:24:40.291 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 4b95f4897fa13f2cd904aee711aeafc0c5295cd8, got: 2852e6e05fbb95076fc091f6d1780f1f8fe35e0f)
2023-12-13 21:24:40.292 PojavLauncher[4311:324098] [MCDL] Downloading library commons-codec:commons-codec:1.10
2023-12-13 21:24:40.720 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 39c7796b469a600f72380316f6b1f11db6c2c7c4, got: 4b95f4897fa13f2cd904aee711aeafc0c5295cd8)
2023-12-13 21:24:40.720 PojavLauncher[4311:324098] [MCDL] Downloading library net.java.jinput:jinput:2.0.5
2023-12-13 21:24:41.054 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: e12fe1fda814bd348c1579329c86943d2cd3c6a6, got: 39c7796b469a600f72380316f6b1f11db6c2c7c4)
2023-12-13 21:24:41.055 PojavLauncher[4311:324098] [MCDL] Downloading library net.java.jutils:jutils:1.0.0
2023-12-13 21:24:41.173 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: c6b7dc51dd44379cc751b7504816006e9be4b1e6, got: e12fe1fda814bd348c1579329c86943d2cd3c6a6)
2023-12-13 21:24:41.174 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:brigadier:1.0.17
2023-12-13 21:24:41.353 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: ebd6690f33871ccee9b6132c6480668ee2e35020, got: c6b7dc51dd44379cc751b7504816006e9be4b1e6)
2023-12-13 21:24:41.354 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:datafixerupper:4.0.26
2023-12-13 21:24:42.365 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: c4ba5371a29ac9b2ad6129b1d39ea38750043eff, got: ebd6690f33871ccee9b6132c6480668ee2e35020)
2023-12-13 21:24:42.365 PojavLauncher[4311:324098] [MCDL] Downloading library com.google.code.gson:gson:2.8.0
2023-12-13 21:24:42.803 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: ad54da276bf59983d02d5ed16fc14541354c71fd, got: c4ba5371a29ac9b2ad6129b1d39ea38750043eff)
2023-12-13 21:24:42.804 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:authlib:2.1.28
2023-12-13 21:24:43.014 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: a698750c16740fd5b3871425f4cb3bbaa87f529d, got: ad54da276bf59983d02d5ed16fc14541354c71fd)
2023-12-13 21:24:43.014 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.commons:commons-compress:1.8.1
2023-12-13 21:24:43.623 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 18f4247ff4572a074444572cee34647c43e7c9c7, got: a698750c16740fd5b3871425f4cb3bbaa87f529d)
2023-12-13 21:24:43.623 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.httpcomponents:httpclient:4.3.3
2023-12-13 21:24:44.728 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f, got: 18f4247ff4572a074444572cee34647c43e7c9c7)
2023-12-13 21:24:44.728 PojavLauncher[4311:324098] [MCDL] Downloading library commons-logging:commons-logging:1.1.3
2023-12-13 21:24:44.912 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 31fbbff1ddbf98f3aa7377c94d33b0447c646b6e, got: f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f)
2023-12-13 21:24:44.912 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.httpcomponents:httpcore:4.3.2
2023-12-13 21:24:46.082 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 5ad88f325e424f8dbc2be5459e21ea5cab3864e9, got: 31fbbff1ddbf98f3aa7377c94d33b0447c646b6e)
2023-12-13 21:24:46.082 PojavLauncher[4311:324098] [MCDL] Downloading library it.unimi.dsi:fastutil:8.2.1
2023-12-13 21:25:17.943 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: e801d13612e22cad62a3f4f3fe7fdbe6334a8e72, got: 5ad88f325e424f8dbc2be5459e21ea5cab3864e9)
2023-12-13 21:25:17.943 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.logging.log4j:log4j-api:2.8.1
2023-12-13 21:25:18.331 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 4ac28ff2f1ddf05dae3043a190451e8c46b73c31, got: e801d13612e22cad62a3f4f3fe7fdbe6334a8e72)
2023-12-13 21:25:18.332 PojavLauncher[4311:324098] [MCDL] Downloading library org.apache.logging.log4j:log4j-core:2.8.1
2023-12-13 21:25:21.225 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl:3.2.1
2023-12-13 21:25:21.226 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl:3.2.2
2023-12-13 21:25:21.226 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.2.1
2023-12-13 21:25:21.226 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.2.2
2023-12-13 21:25:21.227 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.2.1
2023-12-13 21:25:21.231 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.2.2
2023-12-13 21:25:21.231 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.2.1
2023-12-13 21:25:21.232 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.2.2
2023-12-13 21:25:21.232 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: f378f889797edd7df8d32272c06ca80a1b6b0f58, got: 4ac28ff2f1ddf05dae3043a190451e8c46b73c31)
2023-12-13 21:25:21.233 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.2.1
2023-12-13 21:25:21.233 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.2.2
2023-12-13 21:25:21.234 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.2.1
2023-12-13 21:25:21.235 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.2.2
2023-12-13 21:25:21.235 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.2.1
2023-12-13 21:25:21.235 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.2.2
2023-12-13 21:25:21.236 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl:3.2.1
2023-12-13 21:25:21.236 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl:3.2.2
2023-12-13 21:25:21.237 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.2.1
2023-12-13 21:25:21.237 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-jemalloc:3.2.2
2023-12-13 21:25:21.238 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.2.1
2023-12-13 21:25:21.238 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-openal:3.2.2
2023-12-13 21:25:21.239 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.2.1
2023-12-13 21:25:21.239 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-opengl:3.2.2
2023-12-13 21:25:21.240 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.2.1
2023-12-13 21:25:21.240 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-glfw:3.2.2
2023-12-13 21:25:21.240 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.2.1
2023-12-13 21:25:21.240 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.2.2
2023-12-13 21:25:21.241 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-tinyfd:3.2.1
2023-12-13 21:25:21.242 PojavLauncher[4311:324098] [MCDL] Skipped library org.lwjgl:lwjgl-stb:3.2.2
2023-12-13 21:25:21.243 PojavLauncher[4311:324098] [MCDL] Downloading library com.mojang:text2speech:1.11.3
2023-12-13 21:25:21.357 PojavLauncher[4311:324117] [MCDL] SHA1 failed for (null) (expected: 6ef160c3133a78de015830860197602ca1c855d3, got: f378f889797edd7df8d32272c06ca80a1b6b0f58)
2023-12-13 21:25:21.359 PojavLauncher[4311:324098] [MCDL] Skipped library com.mojang:text2speech:1.11.3
2023-12-13 21:25:21.360 PojavLauncher[4311:324098] [MCDL] Skipped library ca.weblite:java-objc-bridge:1.0.0
2023-12-13 21:25:21.362 PojavLauncher[4311:324098] [MCDL] Downloading library ca.weblite:java-objc-bridge:1.0.0
2023-12-13 21:25:22.525 PojavLauncher[4311:324098] [MCDL] Finished: download libraries
2023-12-13 21:25:22.525 PojavLauncher[4311:324098] [MCDL] Begin: download assets
2023-12-13 21:25:29.127 PojavLauncher[4311:324098] [MCDL] Finished: download assets
2023-12-13 21:25:29.408 PojavLauncher[4311:324098] Successfully set Jetsam task limit
2023-12-13 21:25:29.419 PojavLauncher[4311:324117] [MCDL] Warning: couldn't find SHA for /var/mobile/Containers/Data/Application/B11B8F66-4442-4EEE-ABCD-FAA9B8AC9D86/Documents/Library/Application Support/minecraft/versions/Expensive-2.0/Expensive-2.0.json, have to assume it's good.
2023-12-13 21:25:29.429 PojavLauncher[4311:324117] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2023-12-13 21:25:29.429 PojavLauncher[4311:324117] [JavaLauncher] Beginning JVM launch
2023-12-13 21:25:29.429 PojavLauncher[4311:324117] [JavaLauncher] Restored preference: JAVA_HOME is set to /var/containers/Bundle/Application/C5C7876E-315D-47DC-8034-D15D9D0FB7C6/PojavLauncher.app/jvm/java-17-openjdk
2023-12-13 21:25:29.429 PojavLauncher[4311:324117] [JavaLauncher] Restored preference: RENDERER is set to auto
2023-12-13 21:25:29.429 PojavLauncher[4311:324117] [JavaLauncher] Max RAM allocation is set to 1523 MB
2023-12-13 21:25:29.430 PojavLauncher[4311:324117] [JavaLauncher] Java executable path: /var/containers/Bundle/Application/C5C7876E-315D-47DC-8034-D15D9D0FB7C6/PojavLauncher.app/jvm/java-17-openjdk/bin/java
2023-12-13 21:25:29.435 PojavLauncher[4311:324117] [JavaLauncher] Added custom JVM flag: -noverify
2023-12-13 21:25:29.435 PojavLauncher[4311:324117] [Init] Found JLI lib
2023-12-13 21:25:29.435 PojavLauncher[4311:324117] [Init] Calling JLI_Launch
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.lang.System.getenv(String)" is null
	at com.github.caciocavallosilano.cacio.ctc.CTCScreen.<clinit>(CTCScreen.java:140)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.getPlatformWindowFactory(CTCToolkit.java:67)
	at com.github.caciocavallosilano.cacio.peer.CacioToolkit.<init>(CacioToolkit.java:112)
	at com.github.caciocavallosilano.cacio.ctc.CTCToolkit.<init>(CTCToolkit.java:59)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:55)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:49)
Launching Minecraft Expensive-2.0
Library net.java.dev.jna:jna:4.4.0 has been changed to version 5.8.0
Ignored non-exists file: /var/mobile/Containers/Data/Application/B11B8F66-4442-4EEE-ABCD-FAA9B8AC9D86/Documents/Library/Application Support/minecraft/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
Args init finished. Now starting game
2023-12-13 18:25:30,629 main ERROR appender Console has no parameter that matches element Policies
2023-12-13 21:25:30.750 PojavLauncher[4311:324963] Error
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:79)
	... 7 more

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Crash
```

### Expected Behavior

I expected that the cheat client would launch without any problems and its functions would work stably

### Platform

```markdown
- Device model: iPad 2020
- iOS version: 14.7.1
- PojavLauncher version: 2.1
```

### Anything else?

Vanilla versions from 1.20 crash for no reason, just like in cheat clients.

**Comment by GaucovyAero** [comment]
absolutely no idea

**Comment by ItAnthon** [comment]
the reason it crashed is because you’re using an extremely old version of PojavLauncher. use the link below instead.

https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions

**Comment by MogwartUser** [comment]
Thanks

**Comment by ItAnthon** [comment]
Np :D
