### ISSUE TITLE
[Bug] - [main/ERROR]: Found 1 services that failed to load : [fml]

### ISSUE THREAD

**Issue by Dogg3778** [PojavLauncherTeam/PojavLauncher_iOS#663]
### Describe the bug

Startup results in crash

### The log file and images/videos

Latest.log:
[10:50:01] [main/INFO]: ModLauncher running: args [--username, D_ogg, --version, 1.20.1, --gameDir, /var/mobile/Containers/Data/Application/6384D2BA-689A-47AD-BD2E-16C2884D68D9/Documents/Library/Application Support/minecraft, --assetsDir, /var/mobile/Containers/Data/Application/6384D2BA-689A-47AD-BD2E-16C2884D68D9/Documents/Library/Application Support/minecraft/assets, --assetIndex, 5, --uuid, 6acb65b2437746f88b47243ed187cfd6, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, 0, --xuid, 14965154774400072267, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[10:50:01] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8-internal by N/A; OS Mac OS X arch aarch64 version 16.1
[10:50:01] [main/FATAL]: Encountered serious error loading launch plugin service. Things will not work well
java.util.ServiceConfigurationError: cpw.mods.modlauncher.serviceapi.ILaunchPluginService: Provider net.minecraftforge.fml.loading.RuntimeDistCleaner could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderImpl.get(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.util.ServiceLoaderUtils.lambda$streamWithErrorHandling$0(ServiceLoaderUtils.java:39) ~[modlauncher-10.0.9.jar%2387!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.<init>(LaunchPluginHandler.java:46) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:65) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar%2365!/:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/api/distmarker/OnlyIn
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.<clinit>(RuntimeDistCleaner.java:42) ~[fmlloader-1.20.1-47.2.0.jar%2374!/:1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	... 24 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.api.distmarker.OnlyIn
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.<clinit>(RuntimeDistCleaner.java:42) ~[fmlloader-1.20.1-47.2.0.jar%2374!/:1.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	... 24 more
[10:50:01] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[10:50:02] [main/INFO]: Trying GL version 4.6
[10:50:02] [main/INFO]: Requested GL version 4.6 got version 0.0
[10:50:02] [main/ERROR]: Dist Cleaner is missing, we need this to run
[10:50:02] [main/ERROR]: Service failed to load fml
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: Missing DistCleaner, cannot run!
	at net.minecraftforge.fml.loading.FMLLoader.lambda$onInitialLoad$2(FMLLoader.java:94) ~[fmlloader-1.20.1-47.2.0.jar%2374!/:1.0]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.FMLLoader.onInitialLoad(FMLLoader.java:92) ~[fmlloader-1.20.1-47.2.0.jar%2374!/:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.onLoad(FMLServiceProvider.java:100) ~[fmlloader-1.20.1-47.2.0.jar%2374!/:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:116) ~[modlauncher-10.0.9.jar%2387!/:?]
	at java.util.HashMap$Values.forEach(Unknown Source) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:116) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:48) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:88) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2387!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:106) ~[launcher.jar%2365!/:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) ~[launcher.jar%2365!/:?]
[10:50:02] [main/ERROR]: Found 1 services that failed to load : [fml]

### Steps To Reproduce

```markdown
1. Start pojav
2. Install 1.20.1
3. Install forge for 1.20.1 (I tried 47.2.0 and 47.2.21)
4. Try to play minecraft
5. The game will spit out error 1
```

### Expected Behavior

I expected the game to load normally into main menu

### Platform

```markdown
- Device model: iPhone SE 2nd gen
- iOS version: 16.1
- PojavLauncher version: 2.2
```

**Comment by GaucovyAero** [comment]
```cpw.mods.modlauncher.api.IncompatibleEnvironmentException: Missing DistCleaner, cannot run!```
probably a mod related issue

**Comment by GaucovyAero** [comment]
else dunno, try googling

**Comment by Dogg3778** [comment]
I have literally NO mods installed, only forge
Googling tells me to recompile OS

**Comment by GaucovyAero** [comment]
try using a different forge version maybe

**Comment by Dogg3778** [comment]
I clearly stated that I used both recommended and latest. I have never in my life encountered situations that require any other forge versions. Interestingly enough I had mc forge 1.12.2 running smoothly a month ago. Now I’ve tried launching it and it also doesn’t work. I suppose it’s dark magic to blame

**Comment by GaucovyAero** [comment]
> I clearly stated that I used both recommended and latest. I have never in my life encountered situations that require any other forge versions. Interestingly enough I had mc forge 1.12.2 running smoothly a month ago. Now I’ve tried launching it and it also doesn’t work. I suppose it’s dark magic to blame

try sending log of 1.12.2

**Comment by Dogg3778** [comment]
It doesn’t start, instead it now shows invalid URL message. Also I don’t think it’ll help in launching 1.20.1
I’ll try to reinstall pojav now to see if it helps
![C2EF8F9D-0EFB-4723-8610-B37871886A4A](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/102381583/7b6195a4-ac7f-45b2-85b3-d0eb798dcaf7)

**Comment by GaucovyAero** [comment]
the invalid url thing makes sense cause on forge 1.20.1 you are missing a core library of forge, that means you gotta fix that first

**Comment by Dogg3778** [comment]
How do i fix missing library?
Also reinstalling didn’t help, it crashed with the same log

**Comment by GaucovyAero** [comment]
> How do i fix missing library? Also reinstalling didn’t help, it crashed with the same log

you are not able to download stuff, thats the issue

**Comment by GaucovyAero** [comment]
maybe its due to the fact you are in russia? try using a vpn

**Comment by Dogg3778** [comment]
VPN didn’t help, maybe I can try to download manually?

**Comment by Dogg3778** [comment]
![C22D94E5-05B0-4F23-BD50-C9FEC4EC425E](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/102381583/c05aac0a-45ad-4bb6-80f2-34b40f38424e)
![F211F6CF-300F-4E8A-8D30-A7B6F3F2F092](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/102381583/ed4922e4-6a54-4f64-b09b-fbf8b40a6097)
![B9A15563-DFB3-493E-BBD3-3D45516FA4EA](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/assets/102381583/3a8c00ec-82ce-4c4c-970c-7094f8fbca23)
I reinstalled pojav today again, and it had shown me this message while installing 1.20.1, could it be the cause of fml crash?

**Comment by Kiokingz** [comment]
> ![C22D94E5-05B0-4F23-BD50-C9FEC4EC425E](https://private-user-images.githubusercontent.com/102381583/317225280-c05aac0a-45ad-4bb6-80f2-34b40f38424e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTIyMTgsIm5iZiI6MTcxMTg5MTkxOCwicGF0aCI6Ii8xMDIzODE1ODMvMzE3MjI1MjgwLWMwNWFhYzBhLTQ1YWQtNGJiNi04MGYyLTM0YjQwZjM4NDI0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDUyZDZiZTE0MDgxOTNhNDczNGVmNjUxNTFlY2RiYjJmYWU0YjI3MzY0OWIzYTk1NThlYWY1OTk5N2Q3MzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cj-AMGiuhYXmEBfkZe5Oeg24GR78jcFOjHC734DfwF8)
> ![F211F6CF-300F-4E8A-8D30-A7B6F3F2F092](https://private-user-images.githubusercontent.com/102381583/317225322-ed4922e4-6a54-4f64-b09b-fbf8b40a6097.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTIyMTgsIm5iZiI6MTcxMTg5MTkxOCwicGF0aCI6Ii8xMDIzODE1ODMvMzE3MjI1MzIyLWVkNDkyMmU0LTZhNTQtNGY2NC1iMDliLWZiZjhiNDBhNjA5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjFkNDc1NDYxMjYyZThkMTYyMzhjZmMyMmZmMmY4YmVjNTljZGIxNTk5NGIwMDZhZjg3ODk4ZGU3MGNmMmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JTR5TyQNLjD1WExy4kYyI_WguazfFE25bH1XpboYH0E)
> ![B9A15563-DFB3-493E-BBD3-3D45516FA4EA](https://private-user-images.githubusercontent.com/102381583/317225333-3a8c00ec-82ce-4c4c-970c-7094f8fbca23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTIyMTgsIm5iZiI6MTcxMTg5MTkxOCwicGF0aCI6Ii8xMDIzODE1ODMvMzE3MjI1MzMzLTNhOGMwMGVjLTgyY2UtNGM0Yy05NzBjLTcwOTRmOGZiY2EyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzMxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTBlMjRhNmRkNWM5NzhjOWIyZWVhNzA5MjkwODgxNzI1MGUxMGE2MjdhNjJkY2I0ZmYyMTM0OWRlYzRiMDJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hbX8p9FjLJtGMjTDtg-_U3BtSFJLl2pVb8LidRdZQp8)
> I reinstalled pojav today again, and it had shown me this message while installing 1.20.1, could it be the cause of fml crash?

i recommend you attach the entire log file instead of copying it, use the "send your logs" button, and attach it here.

either way this seems like a bad minecraft install, if problem persists even after re-installing minecraft, then i don't know whats happening because i dont know what launcher version are you using
