### ISSUE TITLE
latest PojavLauncher feedback

### ISSUE THREAD

**Issue by lanspring** [PojavLauncherTeam/PojavLauncher_iOS#72]
latest PojavLauncher Installing fabric mod crashes, the old version works normally

**Comment by khanhduytran0** [comment]
Send latestlog.txt

**Comment by lanspring** [comment]
> Send latestlog.txt

2021-02-26 16:23:14.972 PojavLauncher[4633:121326] Found JLI lib
2021-02-26 16:23:14.972 PojavLauncher[4633:121326] Calling JLI_Launch
[0.016s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b834000-0x000000016b840000).
[0.016s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-26 16:23:15.185 PojavLauncher[4633:121320] libpojavexec loaded from vm=0x106b59e50
Finding a version
Selected Minecraft version: fabric-loader-0.11.2-1.14.4
Downloading version list
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Downloading fabric-loader-0.11.2-1.14.4.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading fabric-loader-0.11.2-1.14.4.jar
2021-02-26 16:23:22.318 PojavLauncher[4633:121320] MGLKViewController viewDidLoad
2021-02-26 16:23:22.320 PojavLauncher[4633:121320] Received SurfaceViewController callback, width=1792, height=828
Saving GLES context
Launching Minecraft fabric-loader-0.11.2-1.14.4
Library com.google.guava:guava: Replaced version 21.0 with 21.0
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Args init finished. Now starting game
2021-02-26 16:23:22.937 PojavLauncher[4633:121320] MGLKViewController viewDidAppear
2021-02-26 16:23:22.937 PojavLauncher[4633:121320] MGLKViewController pause
2021-02-26 16:23:22.937 PojavLauncher[4633:121320] MGLKViewController resume
2021-02-26 16:23:22.940 PojavLauncher[4633:121320] MGLKViewController pause
[08:23:23] [Thread-1/INFO]: Loading for game Minecraft 1.14.4
[08:23:23] [Thread-1/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Mod resolution failed!
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:783) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) ~[fabric-loader-0.11.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:116) ~[launcher.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to turn path '5de3e342-bead-478f-bc81-f8a264286619.jar' into URL!
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:605) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:938) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:766) ~[fabric-loader-0.11.2.jar:?]
	... 10 more
Caused by: java.lang.RuntimeException: Failed to turn path '5de3e342-bead-478f-bc81-f8a264286619.jar' into URL!
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.lambda$compute$3(ModResolver.java:712) ~[fabric-loader-0.11.2.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:675) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:714) ~[fabric-loader-0.11.2.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: net.fabricmc.loader.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: jimfs
	at net.fabricmc.loader.util.UrlUtil.asUrl(UrlUtil.java:85) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.lambda$compute$3(ModResolver.java:710) ~[fabric-loader-0.11.2.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:675) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:714) ~[fabric-loader-0.11.2.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.net.MalformedURLException: unknown protocol: jimfs
	at java.net.URL.<init>(URL.java:679) ~[?:?]
	at java.net.URL.<init>(URL.java:568) ~[?:?]
	at net.fabricmc.loader.util.UrlUtil.asUrl(UrlUtil.java:83) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.lambda$compute$3(ModResolver.java:710) ~[fabric-loader-0.11.2.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:675) ~[?:?]
	at net.fabricmc.loader.discovery.ModResolver$UrlProcessAction.compute(ModResolver.java:714) ~[fabric-loader-0.11.2.jar:?]
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

**Comment by khanhduytran0** [comment]
It’s seems not latest build.

**Comment by lanspring** [comment]
I'm sure I downloaded the latest version

**Comment by khanhduytran0** [comment]
But latest build (1.1 prepared to release) ≠ latest version (1.0)

**Comment by lanspring** [comment]
Is this the latest version?github.com/PojavLauncherTeam/PojavLauncher_iOS/releases

**Comment by khanhduytran0** [comment]
Yes, but read that v1.0 has a Fabric API broken.

**Comment by khanhduytran0** [comment]
And this is the latest build: https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions/runs/600924702

**Comment by lanspring** [comment]
Thank you very much for your efforts, v1.1 it can work normally

**Comment by khanhduytran0** [comment]
You're welcome!
