### ISSUE TITLE
[Question] <Launcher Crashes>

### ISSUE THREAD

**Issue by hotkenoqi** [PojavLauncherTeam/PojavLauncher_iOS#741]
### Ask the question here.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2024-08-07 14:15:39
Description: Initializing game

java.lang.ExceptionInInitializerError
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.System.getProperty(String)" is null
	at org.lwjgl.opengl.GL.<clinit>(GL.java:81)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141)
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102)
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (aarch64) version 15.6.1
	Java Version: 17.0.5-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 307003232 bytes (292 MiB) / 499122176 bytes (476 MiB) up to 1015021568 bytes (968 MiB)
	CPUs: 6
	Processor Vendor: Apple Inc.
	Processor Name: Apple processor
	Identifier: Apple Inc. Family 0x462504d2 Model 0 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 3849.78
	Virtual memory used (MB): 2965.84
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -Xms128M -Xmx962M -Xbootclasspath/a:/var/containers/Bundle/Application/AD14F077-22A6-45C6-AA0D-57220910ACFB/PojavLauncher.app/libs_caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/var/containers/Bundle/Application/AD14F077-22A6-45C6-AA0D-57220910ACFB/PojavLauncher.app/libs_caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: vi_VN
	CPU: <unknown>

**Comment by GaucovyAero** [comment]
use the share log file button and get latestlog.txt instead

**Comment by hotkenoqi** [comment]
> use the share log file button and get latestlog.txt instead

https://drive.google.com/drive/folders/1-JP68nItbTAUmxHZPNe_lJpD2UoT6yYW
i dont know how to add file on phone so i upload them on drive instead

**Comment by GaucovyAero** [comment]
your pojav is outdated, use 3.0 actions builds, guide is on the pojav wiki

**Comment by hotkenoqi** [comment]
> your pojav is outdated, use 3.0 actions builds, guide is on the pojav wiki

i want to play v1.20.4 but theres only (Default) in the pojav 3.0 and i download the lastest 2.2

**Comment by GaucovyAero** [comment]
> > your pojav is outdated, use 3.0 actions builds, guide is on the pojav wiki
> 
> i want to play v1.20.4 but theres only (Default) in the pojav 3.0 and i download the lastest 2.2

just switch the version lol
