### ISSUE TITLE
Crash on login (Mojang)

### ISSUE THREAD

**Issue by sourcelocation** [PojavLauncherTeam/PojavLauncher_iOS#79]
I can not log into my account. I am using the latest version. Here is my latestlog.txt:
```

2021-03-02 14:45:03.064 PojavLauncher[7055:511546] Beginning JVM launch
2021-03-02 14:45:03.064 PojavLauncher[7055:511546] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-02 14:45:03.064 PojavLauncher[7055:511546] Reading custom JVM args (overrideargs.txt), opened=0
2021-03-02 14:45:03.065 PojavLauncher[7055:511546] Found JLI lib
2021-03-02 14:45:03.065 PojavLauncher[7055:511546] Calling JLI_Launch
2021-03-02 14:45:03.066 PojavLauncher[7055:511549] Beginning JVM launch
2021-03-02 14:45:03.067 PojavLauncher[7055:511549] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-02 14:45:03.067 PojavLauncher[7055:511549] Found JLI lib
2021-03-02 14:45:03.067 PojavLauncher[7055:511549] Calling JLI_Launch
[0.010s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b218000-0x000000016b224000).
[0.010s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-03-02 14:45:03.242 PojavLauncher[7055:511546] libpojavexec loaded from vm=0x106e2de50
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 549 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:908)
	at com.google.gson.Gson.fromJson(Gson.java:898)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:42)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 549 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:904)
	... 4 more

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001067262b0, pid=7055, tid=771
#
# JRE version: OpenJDK Runtime Environment (16.0) (build 16+0)
# Java VM: OpenJDK 64-Bit Server VM (16+0, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x4522b0]  _ZN16java_lang_String11utf8_lengthEP7oopDescP16typeArrayOopDesc+0x28
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /private/var/mobile/Documents/minecraft/hs_err_pid7055.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

```

**Comment by khanhduytran0** [comment]
Maybe try login against?

**Comment by ExeRhythm** [comment]
Tried, not working

**Comment by 7idge** [comment]
I'm also having this issue. Here's my log:
`2021-03-02 15:29:49.712 PojavLauncher[3078:188232] Beginning JVM launch
2021-03-02 15:29:49.713 PojavLauncher[3078:188232] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-02 15:29:49.713 PojavLauncher[3078:188232] Reading custom JVM args (overrideargs.txt), opened=0
2021-03-02 15:29:49.713 PojavLauncher[3078:188232] Found JLI lib
2021-03-02 15:29:49.713 PojavLauncher[3078:188232] Calling JLI_Launch
2021-03-02 15:29:49.713 PojavLauncher[3078:188239] Beginning JVM launch
2021-03-02 15:29:49.713 PojavLauncher[3078:188239] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-02 15:29:49.713 PojavLauncher[3078:188239] Found JLI lib
2021-03-02 15:29:49.713 PojavLauncher[3078:188239] Calling JLI_Launch
[0.007s][warning][os,thread] Attempt to protect stack guard pages failed (0x0000000169394000-0x00000001693a0000).
[0.007s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-03-02 15:29:49.773 PojavLauncher[3078:188232] libpojavexec loaded from vm=0x108021e50
java.lang.NullPointerException: Cannot read field "accessToken" because "response" is null
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:44)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010791a2b0, pid=3078, tid=771
#
# JRE version: OpenJDK Runtime Environment (16.0) (build 16+0)
# Java VM: OpenJDK 64-Bit Server VM (16+0, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x4522b0]  _ZN16java_lang_String11utf8_lengthEP7oopDescP16typeArrayOopDesc+0x28
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /private/var/mobile/Documents/minecraft/hs_err_pid3078.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#`

**Comment by 7idge** [comment]
I'm also having this issue, here's my log:
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6069746/latestlog.txt)

**Comment by HongyiMC** [comment]
A temporary fix for this problem can be done by:
- deleting /var/mobile/Documents/.pojavlauncher/
- reinstall the pojavlauncher deb file

hope this helps

**Comment by 7idge** [comment]
That didn't work.

**Comment by ExeRhythm** [comment]
Did not work

**Comment by lilkeve** [comment]
I am also having this problem

**Comment by khanhduytran0** [comment]
Update to latest build.

**Comment by 7idge** [comment]
I'm on the latest build. 1.1 correct?

**Comment by khanhduytran0** [comment]
@7idge latest version ≠ latest build

**Comment by Doregon** [comment]
Closing stale issue.
