### ISSUE TITLE
Minecraft 1.8 Not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#87]
I can't open any world on this version - can you fix it?

latestlog.txt

2021-03-08 08:35:25.508 PojavLauncher[30455:1145996] Beginning JVM launch
2021-03-08 08:35:25.509 PojavLauncher[30455:1145996] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-08 08:35:25.509 PojavLauncher[30455:1145996] Reading custom JVM args (overrideargs.txt), opened=0
2021-03-08 08:35:25.509 PojavLauncher[30455:1145996] Found JLI lib
2021-03-08 08:35:25.509 PojavLauncher[30455:1145996] Calling JLI_Launch
2021-03-08 08:35:25.510 PojavLauncher[30455:1145997] Beginning JVM launch
2021-03-08 08:35:25.510 PojavLauncher[30455:1145997] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-08 08:35:25.510 PojavLauncher[30455:1145997] Found JLI lib
2021-03-08 08:35:25.510 PojavLauncher[30455:1145997] Calling JLI_Launch
[0.007s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016b5b0000-0x000000016b5bc000).
[0.007s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-03-08 08:35:25.749 PojavLauncher[30455:1145996] libpojavexec loaded from vm=0x104b59e50
Finding a version
Selected Minecraft version: 1.8
Downloading version list
Downloading 1.8.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl.lwjgl:lwjgl:2.9.1
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.1
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.1
Ignored org.lwjgl.lwjgl:lwjgl:2.9.2-nightly-20140822
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.2-nightly-20140822
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822
Ignored net.java.jinput:jinput-platform:2.0.5
Downloading tv.twitch:twitch-platform:6.5
java.io.IOException: Unable to download from https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.jar
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:35)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:16)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:61)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:709)
	at net.kdt.pojavlaunch.PLaunchApp.lambda$installMinecraft$0(PLaunchApp.java:152)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:30)
	... 5 more
Download failed
Downloading tv.twitch:twitch-external-platform:4.5
java.io.IOException: Unable to download from https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5.jar
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:35)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:16)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:61)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:709)
	at net.kdt.pojavlaunch.PLaunchApp.lambda$installMinecraft$0(PLaunchApp.java:152)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.io.IOException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:30)
	... 5 more
Download failed
Downloading 1.8.jar
2021-03-08 08:35:32.169 PojavLauncher[30455:1145996] MGLKViewController viewDidLoad
2021-03-08 08:35:32.172 PojavLauncher[30455:1145996] Received SurfaceViewController callback, width=1136, height=640
Saving GLES context
Launching Minecraft 1.8
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.1/lwjgl-platform-2.9.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5.jar
2021-03-08 08:35:32.290 PojavLauncher[30455:1145996] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x1029a2190>)
Args init finished. Now starting game
2021-03-08 08:35:32.810 PojavLauncher[30455:1145996] MGLKViewController viewDidAppear
2021-03-08 08:35:32.810 PojavLauncher[30455:1145996] MGLKViewController pause
2021-03-08 08:35:32.810 PojavLauncher[30455:1145996] MGLKViewController resume
2021-03-08 08:35:32.830 PojavLauncher[30455:1145996] MGLKViewController pause
[07:35:33] [Client thread/INFO]: Setting user: Owner
[07:35:33] [Client thread/INFO]: (Session ID is token:0:0)
[07:35:34] [Client thread/INFO]: LWJGL Version: 3.2.3 SNAPSHOT
2021-03-08 08:35:34.841 PojavLauncher[30455:1146049] EGLBridge: Initialized!
2021-03-08 08:35:34.841 PojavLauncher[30455:1146049] EGLBridge: EGLDisplay=0x1029a3ce0, EGLSurface=0x102a79ae0
2021-03-08 08:35:34.844 PojavLauncher[30455:1146049] Using CTX pointer=0x1038b2800, shareCtx=NULL
2021-03-08 08:35:34.850 PojavLauncher[30455:1146049] Making current on window 0x1038b2800
2021-03-08 08:35:34.850 PojavLauncher[30455:1146049] EGLBridge: Trigger an initial swapBuffers
2021-03-08 08:35:34.850 PojavLauncher[30455:1146049] MGLKViewController pause
2021-03-08 08:35:34.850 PojavLauncher[30455:1146049] MGLKViewController resume
2021-03-08 08:35:34.851 PojavLauncher[30455:1146049] libGL = 0x281766400
2021-03-08 08:35:34.853 PojavLauncher[30455:1146049] GL4ES init success
2021-03-08 08:35:34.864 PojavLauncher[30455:1145996] MGLKViewController pause
GLFW: Showing window 4354418688, width=1136, height=640, x=0, y=0, 
Grab: false
LWJGLX: switch fullscreen to true
2021-03-08 08:35:35.721 PojavLauncher[30455:1146049] Using CTX pointer=0x1038b2800, shareCtx=NULL
2021-03-08 08:35:35.721 PojavLauncher[30455:1146049] Making current on window 0x1038b2800
2021-03-08 08:35:35.721 PojavLauncher[30455:1146049] EGLBridge: Trigger an initial swapBuffers
2021-03-08 08:35:35.721 PojavLauncher[30455:1146049] MGLKViewController pause
2021-03-08 08:35:35.721 PojavLauncher[30455:1146049] MGLKViewController resume
2021-03-08 08:35:35.722 PojavLauncher[30455:1146049] libGL = 0x281766400
2021-03-08 08:35:35.722 PojavLauncher[30455:1146049] GL4ES init success
GLFW: Showing window 4354418688, width=1136, height=640, x=0, y=0, 
2021-03-08 08:35:35.730 PojavLauncher[30455:1145996] MGLKViewController pause
[07:35:35] [Client thread/INFO]: Reloading ResourceManager: Default
If on Windows, make sure to provide all of the necessary dll's as specified in the twitchsdk README. Also, make sure to set the PATH environment variable to point to the directory containing the dll's.
[07:35:36] [Client thread/ERROR]: Couldn't initialize twitch stream
[07:35:36] [Sound Library Loader/INFO]: Starting up SoundSystem...
[07:35:36] [Thread-6/INFO]: Initializing LWJGL OpenAL
[07:35:36] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[07:35:36] [Thread-6/INFO]: OpenAL initialized.
[07:35:36] [Sound Library Loader/INFO]: Sound engine started
[07:35:38] [Client thread/INFO]: Created: 512x512 textures-atlas
[07:36:16] [Server thread/INFO]: Starting integrated minecraft server version 1.8
[07:36:16] [Server thread/INFO]: Generating keypair
[07:36:16] [Server thread/INFO]: Preparing start region for level 0
[07:36:17] [Server thread/INFO]: Preparing spawn area: 7%
[07:36:18] [Server thread/INFO]: Preparing spawn area: 14%
[07:36:19] [Server thread/INFO]: Preparing spawn area: 20%
[07:36:20] [Server thread/INFO]: Preparing spawn area: 29%
[07:36:21] [Server thread/INFO]: Preparing spawn area: 39%
[07:36:22] [Server thread/INFO]: Preparing spawn area: 51%
[07:36:23] [Server thread/INFO]: Preparing spawn area: 63%
[07:36:24] [Server thread/INFO]: Preparing spawn area: 73%
[07:36:25] [Server thread/INFO]: Preparing spawn area: 83%
[07:36:26] [Server thread/INFO]: Preparing spawn area: 95%
[07:36:27] [Server thread/INFO]: Changing view distance to 12, from 10
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.PlatformDependent0 (file:/var/mobile/Documents/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar) to field java.nio.DirectByteBuffer.cleaner
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.PlatformDependent0
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Mar 08, 2021 7:36:27 AM io.netty.util.internal.PlatformDependent <clinit>
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[07:36:28] [Server thread/INFO]: Owner[local:E:4b2ad596] logged in with entity id 349 at (-166.5, 67.0, 251.5)
[07:36:28] [Server thread/INFO]: Owner joined the game
Grab: true

(I am constantly kicked out of the game right after opening)

**Comment by lanspring** [comment]
You need to reduce visibility and texture

**Comment by khanhduytran0** [comment]
VBO needs to be enabled.
