### ISSUE TITLE
Segfault on iOS 12.5

### ISSUE THREAD

**Issue by thecoder08** [PojavLauncherTeam/PojavLauncher_iOS#9]
I followed the build instructions, no error messages at all! (btw, this is very rare for me) It produced the debian package, which I transfered to my phone. I then opened up Sileo (just an APT frontend) and installed openjdk-16-jre from procurus repository. I then opened the pojavlauncher deb file in Sileo, and installed it. I see the app on my home screen, and open it. I see the white screen, then it immediately crashes. I run it in the terminal and i get
```
2021-01-09 22:37:24.335 PojavLauncher[6267:657670] Beginning JVM launch                
2021-01-09 22:37:24.340 PojavLauncher[6267:657670] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/compat-1.0.0.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/javafx-mx.jar:/Applications/PojavLauncher.app/libs/jfxrt.jar:/Applications/PojavLauncher.app/libs/jfxswt.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/sfntly-1.0.0.jar:                            
2021-01-09 22:37:24.355 PojavLauncher[6267:657670] Staring logging STDIO as jrelog:V   
zsh: segmentation fault  ./PojavLauncher
```
I dunno if the segfault is a coincidence due to the fact that I ran in a terminal, but still an issue.

I'm using chimera jailbreak 12.5

Package manager is Sileo

Hope this project gets working, it'll be awesome!

**Comment by khanhduytran0** [comment]
You can't start an iOS app directly on command line.

**Comment by khanhduytran0** [comment]
Obtain the crash report when you run from home screen.

**Comment by khanhduytran0** [comment]
(Also you may obtain auto build on [Actions](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/actions))

Hmm, it likely that iOS killed Java JIT attempt.

**Comment by thecoder08** [comment]
where can I find the crash report/log for the app? Its not appearing in settings, presumably because its not from the appstore.

**Comment by khanhduytran0** [comment]
You can find crashes at Settings -> Privacy -> Analytics -> Analytics Data.
Also launcher log at /var/mobile/Documents/minecraft/latestlog.txt

**Comment by thecoder08** [comment]
as I said, I can't see it in settings. Also, the minecraft folder is empty.

**Comment by khanhduytran0** [comment]
Can you try execute 
`/usr/lib/jvm/java-16-openjdk/bin/java -version`?

**Comment by thecoder08** [comment]
openjdk version "16" 2021-03-16                                              
OpenJDK Runtime Environment (build 16+0)                                     
OpenJDK 64-Bit Server VM (build 16+0, mixed mode)

**Comment by khanhduytran0** [comment]
Maybe try latest action build?

**Comment by aspenluxxxy** [comment]
> Obtain the crash report when you run from home screen.

Erm, it's not appearing on the homescreen for me, even after running `uicache` and respringing.

**Comment by thecoder08** [comment]
better news, we're now getting a latestlog.txt! This is what it looks like (It abruptly stops so you might be right about ios killing jit):
```
2021-01-31 21:19:01.971 PojavLauncher[4955:178270] Found JLI lib
2021-01-31 21:19:01.972 PojavLauncher[4955:178270] Calling JLI_Launch
[0.018s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016d048000-0x000000016d054000).
[0.019s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-01-31 21:19:02.450 PojavLauncher[4955:178267] libpojavexec loaded from vm=0x101c71e50
```

**Comment by thecoder08** [comment]
this is on action build btw

**Comment by khanhduytran0** [comment]
You can see
```
We are on java now! Starting UI...
```
So java was already ran. Then it seems fails attempt on starting UI (call `UIApplicationMain`) so you ran from command line???

Remember that
> You can't start an iOS app directly on command line.

**Comment by thecoder08** [comment]
no, i didn't. Ran from home screen, saw a BLACK screen this time, and then it crashed so It went back out to home screen.

**Comment by thecoder08** [comment]
also there's still nothing in crashreporter

**Comment by khanhduytran0** [comment]
Follow #16

**Comment by thecoder08** [comment]
Ok I updated to iOS 12.5.1 and I am on release 1.0. I get to the Black screen with buttons, then it loads minecraft and i see the red loading screen, then it gets to the home screen. I can tap Singleplayer, but when I create a world it crashes. I'll send latestlog.txt and some screenshots

**Comment by khanhduytran0** [comment]
Are you on 1GB RAM device?

**Comment by thecoder08** [comment]
yep, iphone 5s. Why, do I need more memory?

latestlog.txt:
```
2021-02-23 15:16:45.433 PojavLauncher[16392:730463] Found JLI lib
2021-02-23 15:16:45.433 PojavLauncher[16392:730463] Calling JLI_Launch
[0.074s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016dc50000-0x000000016dc5c000).
[0.087s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-02-23 15:16:46.225 PojavLauncher[16392:730456] libpojavexec loaded from vm=0x102359e50
java.lang.RuntimeException: Can't connect to the server
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.makeRequest(YggdrasilAuthenticator.java:70)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.authenticate(YggdrasilAuthenticator.java:94)
	at net.kdt.pojavlaunch.authenticator.mojang.LoginTask.run(LoginTask.java:19)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:39)
Caused by: java.net.UnknownHostException: authserver.mojang.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.makeRequest(YggdrasilAuthenticator.java:30)
	... 3 more

2021-02-23 15:17:22.380 PojavLauncher[16392:730456] Returning local object of class NSString
Finding a version
Selected Minecraft version: 1.16.5
Downloading version list
Error: Unable to download from https://launchermeta.mojang.com/mc/game/version_manifest.json
java.io.IOException: Unable to download from https://launchermeta.mojang.com/mc/game/version_manifest.json
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:35)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:16)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadString(DownloadUtils.java:49)
	at net.kdt.pojavlaunch.PLaunchApp.lambda$installMinecraft$0(PLaunchApp.java:98)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.UnknownHostException: launchermeta.mojang.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:27)
	... 4 more
Downloading 1.16.5.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading 1.16.5.jar
2021-02-23 15:17:33.394 PojavLauncher[16392:730456] MGLKViewController viewDidLoad
2021-02-23 15:17:33.402 PojavLauncher[16392:730456] Received SurfaceViewController callback, width=1136, height=640
Saving GLES context
Launching Minecraft 1.16.5
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Args init finished. Now starting game
2021-02-23 15:17:34.907 PojavLauncher[16392:730456] MGLKViewController viewDidAppear
2021-02-23 15:17:34.907 PojavLauncher[16392:730456] MGLKViewController pause
2021-02-23 15:17:34.907 PojavLauncher[16392:730456] MGLKViewController resume
2021-02-23 15:17:34.945 PojavLauncher[16392:730456] MGLKViewController pause
[20:18:18] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:18:18] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:125) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:94) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at djz.a(SourceFile:625) ~[1.16.5.jar:?]
	at djz.<init>(SourceFile:409) ~[1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) ~[1.16.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:116) ~[launcher.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.net.UnknownHostException: api.minecraftservices.com
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
	at java.net.Socket.connect(Socket.java:645) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1277) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:104) ~[authlib-2.1.28.jar:?]
	... 12 more
[20:18:18] [Render thread/INFO]: Setting user: ClassName
[20:18:19] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
2021-02-23 15:18:19.686 PojavLauncher[16392:730716] EGLBridge: Initialized!
2021-02-23 15:18:19.686 PojavLauncher[16392:730716] EGLBridge: EGLDisplay=0x1004e1170, EGLSurface=0x1005d2a10
2021-02-23 15:18:19.779 PojavLauncher[16392:730716] Using CTX pointer=0x1008d3c00, shareCtx=NULL
2021-02-23 15:18:19.783 PojavLauncher[16392:730716] Making current on window 0x1008d3c00
2021-02-23 15:18:19.784 PojavLauncher[16392:730716] EGLBridge: Trigger an initial swapBuffers
2021-02-23 15:18:19.784 PojavLauncher[16392:730716] MGLKViewController pause
2021-02-23 15:18:19.784 PojavLauncher[16392:730716] MGLKViewController resume
2021-02-23 15:18:19.790 PojavLauncher[16392:730456] MGLKViewController pause
2021-02-23 15:18:19.846 PojavLauncher[16392:730716] libGL = 0x2826f1900
2021-02-23 15:18:19.915 PojavLauncher[16392:730716] GL4ES init success
[20:18:33] [Render thread/ERROR]: Error while loading the narrator : java.lang.UnsatisfiedLinkError: /private/var/mobile/Containers/Data/Application/64676950-2CFF-43A6-B174-D4284C567671/tmp/jna--1068855134/jna17684308850145182729.tmp: dlopen(/private/var/mobile/Containers/Data/Application/64676950-2CFF-43A6-B174-D4284C567671/tmp/jna--1068855134/jna17684308850145182729.tmp, 1): no suitable image found.  Did find:
	/private/var/mobile/Containers/Data/Application/64676950-2CFF-43A6-B174-D4284C567671/tmp/jna--1068855134/jna17684308850145182729.tmp: no matching architecture in universal wrapper
	/private/var/mobile/Containers/Data/Application/64676950-2CFF-43A6-B174-D4284C567671/tmp/jna--1068855134/jna17684308850145182729.tmp: no matching architecture in universal wrapper
[20:18:34] [Render thread/INFO]: Reloading ResourceManager: Default
[20:18:37] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/end/end.ogg does not exist, cannot add it to event minecraft:music.end
[20:18:37] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/nether/soulsand_valley/so_below.ogg does not exist, cannot add it to event minecraft:music.nether.basalt_deltas
[20:18:37] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/nether/nether_wastes/rubedo.ogg does not exist, cannot add it to event minecraft:music.nether.nether_wastes
[20:18:37] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/nether/soulsand_valley/so_below.ogg does not exist, cannot add it to event minecraft:music.nether.soul_sand_valley
[20:18:38] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/nether/crimson_forest/chrysopoeia.ogg does not exist, cannot add it to event minecraft:music.nether.crimson_forest
[20:18:38] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/water/shuniji.ogg does not exist, cannot add it to event minecraft:music.under_water
[20:18:38] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/water/dragon_fish.ogg does not exist, cannot add it to event minecraft:music.under_water
[20:18:38] [Worker-Main-2/WARN]: File minecraft:sounds/music/game/water/axolotl.ogg does not exist, cannot add it to event minecraft:music.under_water
[20:18:38] [Worker-Main-2/WARN]: File minecraft:sounds/records/pigstep.ogg does not exist, cannot add it to event minecraft:music_disc.pigstep
2021-02-23 15:19:08.337 PojavLauncher[16392:730844] PBItemCollectionServicer connection disconnected.
[20:20:20] [Render thread/INFO]: OpenAL initialized.
[20:20:20] [Render thread/INFO]: Sound engine started
[20:20:38] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[20:20:39] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[20:20:39] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:20:39] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:20:39] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:20:39] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:20:39] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:20:54] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:23:43] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:23:43] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:23:43] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:23:44] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[20:23:45] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[20:23:45] [Render thread/INFO]: Reloading ResourceManager: Default
[20:24:08] [Render thread/INFO]: Loaded 7 recipes
[20:24:13] [Render thread/INFO]: Loaded 927 advancements
[20:24:44] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:24:45] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[20:24:45] [Server thread/INFO]: Generating keypair
[20:25:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
```
screenshots:

![image](https://user-images.githubusercontent.com/60859253/108911571-682aba00-75f5-11eb-8ad4-b017501c21a4.png)

![image](https://user-images.githubusercontent.com/60859253/108911613-7b3d8a00-75f5-11eb-9045-95ce895406b4.png)

![image](https://user-images.githubusercontent.com/60859253/108911648-885a7900-75f5-11eb-8491-e242224f4502.png)

**Comment by thecoder08** [comment]
i was in offline mode during this, but mojang login does the same thing

**Comment by khanhduytran0** [comment]
On 1GB RAM devices, JVM only takes 256MB as default, so it will not enough for joining world.

**Comment by khanhduytran0** [comment]
Update to latest build, create overrideargs.txt inside minecraft folder, put in `-Xmx512M` and try again.

**Comment by thecoder08** [comment]
Hmm.... It seems that with that i don't even get to the main screen... I just crash right before the screen changes
