### ISSUE TITLE
Minecraft 21w10a and higher snapshots are not working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [PojavLauncherTeam/PojavLauncher_iOS#91]
Not opening

Latest log:

2021-03-10 19:11:17.054 PojavLauncher[61552:2272006] Beginning JVM launch
2021-03-10 19:11:17.055 PojavLauncher[61552:2272006] Warning: chmod +x java failed
2021-03-10 19:11:17.055 PojavLauncher[61552:2272006] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-10 19:11:17.055 PojavLauncher[61552:2272006] Reading custom JVM args (overrideargs.txt), opened=0
2021-03-10 19:11:17.057 PojavLauncher[61552:2272006] Found JLI lib
2021-03-10 19:11:17.057 PojavLauncher[61552:2272006] Calling JLI_Launch
2021-03-10 19:11:17.057 PojavLauncher[61552:2272012] Beginning JVM launch
2021-03-10 19:11:17.057 PojavLauncher[61552:2272012] Warning: chmod +x java failed
2021-03-10 19:11:17.057 PojavLauncher[61552:2272012] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/ExagearApacheCommons.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2021-03-10 19:11:17.057 PojavLauncher[61552:2272012] Found JLI lib
2021-03-10 19:11:17.057 PojavLauncher[61552:2272012] Calling JLI_Launch
[0.006s][warning][os,thread] Attempt to protect stack guard pages failed (0x000000016daf8000-0x000000016db04000).
[0.006s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
2021-03-10 19:11:17.301 PojavLauncher[61552:2272006] libpojavexec loaded from vm=0x1023b9e50
Finding a version
Selected Minecraft version: 21w10a
Downloading version list
Downloading 21w10a.json assets info
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl:3.2.1
Ignored org.lwjgl:lwjgl:3.2.2
Ignored org.lwjgl:lwjgl-jemalloc:3.2.1
Ignored org.lwjgl:lwjgl-jemalloc:3.2.2
Ignored org.lwjgl:lwjgl-openal:3.2.1
Ignored org.lwjgl:lwjgl-openal:3.2.2
Ignored org.lwjgl:lwjgl-opengl:3.2.1
Ignored org.lwjgl:lwjgl-opengl:3.2.2
Ignored org.lwjgl:lwjgl-glfw:3.2.1
Ignored org.lwjgl:lwjgl-glfw:3.2.2
Ignored org.lwjgl:lwjgl-stb:3.2.1
Ignored org.lwjgl:lwjgl-tinyfd:3.2.2
Ignored org.lwjgl:lwjgl-tinyfd:3.2.1
Ignored org.lwjgl:lwjgl-stb:3.2.2
Downloading 21w10a.jar
2021-03-10 19:11:22.065 PojavLauncher[61552:2272006] MGLKViewController viewDidLoad
2021-03-10 19:11:22.067 PojavLauncher[61552:2272006] Received SurfaceViewController callback, width=1136, height=640
Saving GLES context
Launching Minecraft 21w10a
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar
Ignored non-exists file: /var/mobile/Documents/minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
2021-03-10 19:11:22.161 PojavLauncher[61552:2272006] Keyboard cannot present view controllers (attempted to present <SurfaceViewController: 0x1006a9160>)
Args init finished. Now starting game
2021-03-10 19:11:22.683 PojavLauncher[61552:2272006] MGLKViewController viewDidAppear
2021-03-10 19:11:22.683 PojavLauncher[61552:2272006] MGLKViewController pause
2021-03-10 19:11:22.683 PojavLauncher[61552:2272006] MGLKViewController resume
2021-03-10 19:11:22.685 PojavLauncher[61552:2272006] MGLKViewController pause
[18:11:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:11:28] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at dse.a(SourceFile:636) ~[21w10a.jar:?]
	at dse.<init>(SourceFile:407) ~[21w10a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:178) ~[21w10a.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129) ~[launcher.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:11:28] [Render thread/INFO]: Setting user: Owner
[18:11:28] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
2021-03-10 19:11:28.942 PojavLauncher[61552:2272053] EGLBridge: Initialized!
2021-03-10 19:11:28.942 PojavLauncher[61552:2272053] EGLBridge: EGLDisplay=0x1006aa8f0, EGLSurface=0x1006b4af0
2021-03-10 19:11:28.957 PojavLauncher[61552:2272053] Using CTX pointer=0x101107400, shareCtx=NULL
2021-03-10 19:11:28.958 PojavLauncher[61552:2272053] Making current on window 0x101107400
2021-03-10 19:11:28.958 PojavLauncher[61552:2272053] EGLBridge: Trigger an initial swapBuffers
2021-03-10 19:11:28.958 PojavLauncher[61552:2272053] MGLKViewController pause
2021-03-10 19:11:28.958 PojavLauncher[61552:2272053] MGLKViewController resume
2021-03-10 19:11:28.959 PojavLauncher[61552:2272053] libGL = 0x283ceec40
2021-03-10 19:11:28.961 PojavLauncher[61552:2272053] GL4ES init success
2021-03-10 19:11:28.969 PojavLauncher[61552:2272006] MGLKViewController pause
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 3/10/21, 6:11 PM
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at ejd.a(SourceFile:392)
	at dse.<init>(SourceFile:591)
	at net.minecraft.client.main.Main.main(SourceFile:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: wo: Invalid shaders/core/blit_screen.json: d2j fail translate: java.lang.RuntimeException: can not merge I and Z
	at com.googlecode.dex2jar.ir.TypeClass.merge(TypeClass.java:100)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeRef.updateTypeClass(TypeTransformer.java:174)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.copyTypes(TypeTransformer.java:311)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.fixTypes(TypeTransformer.java:226)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(TypeTransformer.java:207)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(TypeTransformer.java:44)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:161)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:433)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:129)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:528)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:425)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:441)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:123)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:271)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

	at wo.a(SourceFile:48)
	at ejv.<init>(SourceFile:197)
	at ejd.a(SourceFile:384)
	... 8 more
Caused by: java.lang.RuntimeException: d2j fail translate: java.lang.RuntimeException: can not merge I and Z
	at com.googlecode.dex2jar.ir.TypeClass.merge(TypeClass.java:100)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeRef.updateTypeClass(TypeTransformer.java:174)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.copyTypes(TypeTransformer.java:311)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.fixTypes(TypeTransformer.java:226)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer$TypeAnalyze.analyze(TypeTransformer.java:207)
	at com.googlecode.dex2jar.ir.ts.TypeTransformer.transform(TypeTransformer.java:44)
	at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:161)
	at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:433)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:42)
	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:129)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:528)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:425)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:441)
	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:123)
	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:271)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:107)
	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
	at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:33)

	at org.apache.commons.io.FilenameUtils.doGetFullPath(Unknown Source)
	at org.apache.commons.io.FilenameUtils.getFullPath(Unknown Source)
	at s.a(SourceFile:95)
	at ejv.a(SourceFile:235)
	at ejv.<init>(SourceFile:179)
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ejd.a(SourceFile:392)
	at dse.<init>(SourceFile:591)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.kdt.pojavlaunch.Tools.lambda$launchMinecraft$0(Tools.java:129)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 21w10a
	Minecraft Version ID: 21w10a
	Operating System: Mac OS X (aarch64) version 14.4
	Java Version: 16, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 122024616 bytes (116 MB) / 437256192 bytes (417 MB) up to 528482304 bytes (504 MB)
	CPUs: 2
	JVM Flags: 0 total; 
	Launched Version: 21w10a
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /var/mobile/Documents/minecraft/crash-reports/crash-2021-03-10_18.11.31-client.txt
LIBGL: Initialising gl4es
LIBGL: v1.1.4 built on Jan 27 2021 06:00:24
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware test on current Context...
LIBGL: Hardware Full NPOT detected and used
LIBGL: Extension GL_EXT_blend_minmax  detected and used
LIBGL: Extension GL_EXT_draw_buffers  detected and used
LIBGL: FBO are in core, and so used
LIBGL: PointSprite are in core, and so used
LIBGL: CubeMap are in core, and so used
LIBGL: BlendColor is in core, and so used
LIBGL: Blend Substract is in core, and so used
LIBGL: Blend Function and Equation Separation is in core, and so used
LIBGL: Texture Mirrored Repeat is in core, and so used
LIBGL: Extension GL_OES_mapbuffer  detected
LIBGL: Extension GL_OES_element_index_uint  detected and used
LIBGL: Extension GL_OES_packed_depth_stencil  detected and used
LIBGL: Extension GL_OES_depth24  detected and used
LIBGL: Extension GL_OES_rgb8_rgba8  detected and used
LIBGL: Extension GL_EXT_texture_format_BGRA8888  detected and used
LIBGL: Extension GL_OES_depth_texture  detected and used
LIBGL: Extension GL_EXT_texture_rg  detected and used
LIBGL: Extension GL_OES_texture_float  detected and used
LIBGL: Extension GL_OES_texture_half_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_float  detected and used
LIBGL: Extension GL_EXT_color_buffer_half_float  detected and used
LIBGL: high precision float in fragment shader available and used
LIBGL: Extension GL_EXT_frag_depth  detected and used
LIBGL: Max vertex attrib: 16
LIBGL: Extension GL_OES_standard_derivatives  detected and used
LIBGL: Max texture size: 16384
LIBGL: Max Varying Vector: 31
LIBGL: Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
LIBGL: Extension GL_EXT_texture_filter_anisotropic  detected and used
LIBGL: Max Anisotropic filtering: 16
LIBGL: Max Color Attachments: 4 / Draw buffers: 4
LIBGL: Hardware vendor is Google Inc.
LIBGL: GLSL 300 es supported and used
LIBGL: ignore MipMap
LIBGL: Targeting OpenGL 2.1
LIBGL: NPOT texture handled in hardware
LIBGL: Not trying to batch small subsequent glDrawXXXX
LIBGL: try to use VBO
LIBGL: Current folder is:/private/var/mobile/Documents/minecraft
LIBGL: Shuting down

**Comment by jawshoeadan** [comment]
Same issue here, this is likely because of the new OpenGL engine that they switched to in this snapshot. Here's my latestlog.txt
[latestlog 2.txt](https://github.com/PojavLauncherTeam/PojavLauncher_iOS/files/6118486/latestlog.2.txt)

**Comment by khanhduytran0** [comment]
Yes. 21w10a now uses GL 3.x - GLSL 1.50 which have several parts not working properly.

**Comment by BowlineNetwork** [comment]
> Yes. 21w10a now uses GL 3.x - GLSL 1.50 which have several parts not working properly.

Can it be fixed easily? I assume all new versions from now on will use that as well.

**Comment by admin-elvistrujanovic** [comment]
What's new about this issue - will this issue be resolved soon?

**Comment by Doregon** [comment]
It’s tbd, we’re waiting and also trying to figure out how to go about it.

**Comment by admin-elvistrujanovic** [comment]
> It’s tbd, we’re waiting and also trying to figure out how to go about it.

Ok, Good Luck

**Comment by rscAvePlex** [comment]
> What's new about this issue - will this issue be resolved soon?

you dare to download java 16 and put it to pojav?

**Comment by Doregon** [comment]
> > What's new about this issue - will this issue be resolved soon?
> 
> you dare to download java 16 and put it to pojav?

Java 16 is the only supported version at the moment. Before you make comments you should make sure you know what you’re talking about. @rscAvePlex

**Comment by rscAvePlex** [comment]
my bad, sorry.

**Comment by admin-elvistrujanovic** [comment]
This issue is closed because of issue duplicate - view #184
